export type Product = {
  id: string;
  name: string;
  category: string; // category slug
  subcategory: string;
  price: number; // PKR
  discount?: number; // percent off, applied to `price` as the original
  rating: number;
  reviews: number;
  description: string;
  material: string;
  color: string;
  style: string;
  rooms: string[]; // room slugs
  dimensions: string;
  inStock: boolean;
  imageKey: string;
  gallery: string[];
  tags: string[];
  isNew?: boolean;
  isBestSeller?: boolean;
  isLuxury?: boolean;
  isHandmade?: boolean;
  popularity: number;
};

export type Category = {
  slug: string;
  name: string;
  imageKey: string;
  blurb: string;
  subcategories: string[];
};

export type Room = {
  slug: string;
  name: string;
  imageKey: string;
  blurb: string;
};

export const DELIVERY_FEE = 250;
export const FREE_DELIVERY_THRESHOLD = 10000;

export const formatPKR = (value: number): string =>
  `₨${Math.round(value).toLocaleString("en-PK")}`;

export const finalPrice = (p: Product): number =>
  p.discount ? Math.round(p.price * (1 - p.discount / 100)) : p.price;

export const CATEGORIES: Category[] = [
  {
    slug: "wall-decor",
    name: "Wall Decor",
    imageKey: "wall-decor",
    blurb: "Art, frames and hangings that give a wall its voice.",
    subcategories: [
      "Wall Stickers",
      "Wall Decals",
      "Paintings",
      "Canvas Art",
      "Posters",
      "Wall Quotes",
      "Wall Letters",
      "Wall Clocks",
      "Photo Frames",
      "Collage Frames",
      "Wall Shelves",
      "Tapestries",
      "Macramé Wall Hangings",
      "Decorative Plates",
      "3D Wall Panels",
      "Islamic Wall Art",
    ],
  },
  {
    slug: "showpieces",
    name: "Showpieces & Sculptures",
    imageKey: "showpieces",
    blurb: "Sculptural objects with quiet presence.",
    subcategories: [
      "Table Showpieces",
      "Animal Figurines",
      "Human Figurines",
      "Couple Figurines",
      "Abstract Sculptures",
      "Mini Statues",
      "Ceramic Showpieces",
      "Glass Showpieces",
      "Metal Sculptures",
      "Resin Art",
      "Decorative Objects",
    ],
  },
  {
    slug: "plants",
    name: "Plants & Artificial Greenery",
    imageKey: "plants",
    blurb: "Evergreen botanicals that never ask for water.",
    subcategories: [
      "Artificial Plants",
      "Artificial Flowers",
      "Artificial Vines",
      "Succulents",
      "Bonsai",
      "Mini Plants",
      "Hanging Plants",
      "Decorative Plant Pots",
      "Planters",
      "Terrariums",
    ],
  },
  {
    slug: "lighting",
    name: "Decorative Lighting",
    imageKey: "lighting",
    blurb: "Warm light, softly shaped.",
    subcategories: [
      "Table Lamps",
      "Decorative Lamps",
      "Bedside Lamps",
      "LED Lights",
      "LED Strip Lights",
      "Fairy Lights",
      "String Lights",
      "Neon Signs",
      "Night Lights",
      "Lanterns",
    ],
  },
  {
    slug: "candles",
    name: "Candles & Home Fragrance",
    imageKey: "candles",
    blurb: "Scent as the final layer of a room.",
    subcategories: [
      "Scented Candles",
      "Decorative Candles",
      "Candle Sets",
      "Candle Holders",
      "Tealight Holders",
      "Wax Melts",
      "Reed Diffusers",
      "Room Sprays",
      "Aroma Diffusers",
      "Incense Holders",
    ],
  },
  {
    slug: "mirrors",
    name: "Mirrors",
    imageKey: "mirrors",
    blurb: "Light, doubled.",
    subcategories: [
      "Round Mirrors",
      "Arched Mirrors",
      "Geometric Mirrors",
      "Decorative Mirrors",
      "LED Mirrors",
      "Full-Length Mirrors",
      "Hanging Mirrors",
    ],
  },
  {
    slug: "rugs",
    name: "Rugs & Floor Decor",
    imageKey: "rugs",
    blurb: "Texture underfoot, warmth throughout.",
    subcategories: [
      "Area Rugs",
      "Round Rugs",
      "Runner Rugs",
      "Shaggy Rugs",
      "Persian-Style Rugs",
      "Modern Rugs",
      "Boho Rugs",
      "Doormats",
      "Floor Cushions",
      "Poufs",
    ],
  },
  {
    slug: "soft-decor",
    name: "Soft Decor",
    imageKey: "soft-decor",
    blurb: "Linen, wool and boucle in considered tones.",
    subcategories: [
      "Cushion Covers",
      "Throw Pillows",
      "Decorative Throws",
      "Blankets",
      "Bolster Covers",
      "Decorative Textiles",
    ],
  },
  {
    slug: "curtains",
    name: "Window & Curtain Decor",
    imageKey: "curtains",
    blurb: "How daylight enters the room.",
    subcategories: [
      "Curtains",
      "Sheer Curtains",
      "Curtain Tiebacks",
      "Curtain Rings",
      "Curtain Rods",
      "Blinds",
      "Window Stickers",
      "Window Films",
    ],
  },
  {
    slug: "vases",
    name: "Vases & Decorative Containers",
    imageKey: "vases",
    blurb: "Vessels worth looking at, empty or full.",
    subcategories: [
      "Ceramic Vases",
      "Glass Vases",
      "Metal Vases",
      "Floor Vases",
      "Mini Vases",
      "Decorative Bottles",
      "Decorative Jars",
      "Decorative Bowls",
      "Decorative Trays",
    ],
  },
  {
    slug: "storage",
    name: "Decorative Storage & Organizers",
    imageKey: "storage",
    blurb: "Order, beautifully contained.",
    subcategories: [
      "Decorative Baskets",
      "Storage Baskets",
      "Decorative Boxes",
      "Jewelry Boxes",
      "Trinket Boxes",
      "Key Holders",
      "Magazine Holders",
      "Tissue Box Covers",
      "Remote Holders",
      "Desk Organizers",
    ],
  },
  {
    slug: "tabletop",
    name: "Tabletop & Centerpiece Decor",
    imageKey: "tabletop",
    blurb: "The table, set for more than dinner.",
    subcategories: [
      "Table Runners",
      "Placemats",
      "Centerpieces",
      "Fruit Baskets",
      "Decorative Bowls",
      "Candle Holders",
      "Napkin Holders",
      "Coasters",
      "Table Vases",
      "Tabletop Sculptures",
    ],
  },
  {
    slug: "entryway",
    name: "Door & Entryway Decor",
    imageKey: "entryway",
    blurb: "The first impression of a home.",
    subcategories: [
      "Door Signs",
      "Welcome Signs",
      "Door Stickers",
      "Door Hangings",
      "Wreaths",
      "Key Holders",
      "Decorative Hooks",
      "Doormats",
    ],
  },
  {
    slug: "kids",
    name: "Kids' Room Decor",
    imageKey: "kids",
    blurb: "Gentle, grown-up decor for small rooms.",
    subcategories: [
      "Kids' Wall Stickers",
      "Cartoon Posters",
      "Name Signs",
      "Growth Charts",
      "Night Lights",
      "Decorative Shelves",
      "Toy Baskets",
      "Dream Catchers",
      "Kids' Rugs",
    ],
  },
  {
    slug: "outdoor",
    name: "Balcony & Outdoor Decor",
    imageKey: "outdoor",
    blurb: "Evenings outside, softly lit.",
    subcategories: [
      "Outdoor Decorative Lights",
      "Solar Lights",
      "Artificial Plants",
      "Plant Hangers",
      "Decorative Pots",
      "Lanterns",
      "Wind Chimes",
      "Garden Ornaments",
      "Outdoor Rugs",
    ],
  },
  {
    slug: "diy",
    name: "DIY & Craft Decor",
    imageKey: "diy",
    blurb: "Make something for your own walls.",
    subcategories: [
      "DIY Wall Art Kits",
      "Paint Kits",
      "Resin Decor",
      "Macramé Kits",
      "Candle-Making Kits",
      "Craft Kits",
      "Decorative Stickers",
    ],
  },
  {
    slug: "personalized",
    name: "Personalized Decor",
    imageKey: "personalized",
    blurb: "Made once, for one home.",
    subcategories: [
      "Custom Name Plates",
      "Family Name Signs",
      "Personalized Frames",
      "Custom Wall Art",
      "Custom Neon Signs",
      "Personalized Cushions",
      "Custom Quotes",
      "Custom Door Signs",
      "Couple Decor",
      "Baby Name Decor",
    ],
  },
  {
    slug: "festive",
    name: "Festive & Seasonal Decor",
    imageKey: "festive",
    blurb: "For the evenings that matter most.",
    subcategories: [
      "Ramadan Decor",
      "Eid Decor",
      "Wedding Decor",
      "Birthday Decor",
      "Valentine's Decor",
      "Christmas Decor",
      "New Year Decor",
      "Festive Lights",
      "Decorative Banners",
    ],
  },
  {
    slug: "islamic",
    name: "Islamic & Cultural Decor",
    imageKey: "islamic",
    blurb: "Calligraphy, geometry and heritage.",
    subcategories: [
      "Arabic Calligraphy",
      "Quranic Wall Art",
      "Ayat Frames",
      "Islamic Geometric Art",
      "Ramadan Lanterns",
      "Islamic Table Decor",
      "Traditional Pottery",
      "Cultural Wall Art",
    ],
  },
  {
    slug: "handmade",
    name: "Handmade & Artisan Decor",
    imageKey: "handmade",
    blurb: "Made slowly, by hand, in small batches.",
    subcategories: [
      "Handmade Pottery",
      "Hand-painted Vases",
      "Handmade Baskets",
      "Wooden Decor",
      "Rattan Decor",
      "Resin Art",
      "Handmade Candles",
      "Handcrafted Sculptures",
      "Embroidered Wall Art",
    ],
  },
];

export const ROOMS: Room[] = [
  {
    slug: "living",
    name: "Living Room",
    imageKey: "room-living",
    blurb: "Layered art, sculptural vases and warm light.",
  },
  {
    slug: "bedroom",
    name: "Bedroom",
    imageKey: "room-bedroom",
    blurb: "Soft textiles, low light and calm surfaces.",
  },
  {
    slug: "dining",
    name: "Dining Area",
    imageKey: "room-dining",
    blurb: "Centerpieces, candlelight and linen.",
  },
  {
    slug: "bathroom",
    name: "Bathroom",
    imageKey: "room-bathroom",
    blurb: "Brass, stone and a quiet scent.",
  },
  {
    slug: "kids",
    name: "Kids Room",
    imageKey: "room-kids",
    blurb: "Playful pieces in a grown-up palette.",
  },
  {
    slug: "balcony",
    name: "Balcony",
    imageKey: "room-balcony",
    blurb: "String lights, planters and evening air.",
  },
  {
    slug: "entrance",
    name: "Entrance",
    imageKey: "room-entrance",
    blurb: "Mirrors, wreaths and a welcoming console.",
  },
  {
    slug: "office",
    name: "Home Office",
    imageKey: "room-office",
    blurb: "Focused, uncluttered and warmly lit.",
  },
];

export const CATEGORY_BY_SLUG = new Map(CATEGORIES.map((c) => [c.slug, c]));
export const ROOM_BY_SLUG = new Map(ROOMS.map((r) => [r.slug, r]));
export const categoryName = (slug: string) => CATEGORY_BY_SLUG.get(slug)?.name ?? slug;
export const roomName = (slug: string) => ROOM_BY_SLUG.get(slug)?.name ?? slug;

export const PRODUCTS: Product[] = [
  // ---------- Wall Decor ----------
  {
    id: "lh-001",
    name: "Dune Horizon Canvas Triptych",
    category: "wall-decor",
    subcategory: "Canvas Art",
    price: 18500,
    discount: 15,
    rating: 4.8,
    reviews: 126,
    description:
      "A three-panel canvas study of drifting dune light, printed on heavyweight cotton canvas and stretched over kiln-dried pine. The muted greys sit quietly against ivory and beige walls.",
    material: "Cotton canvas, pine frame",
    color: "Ivory",
    style: "Modern",
    rooms: ["living", "office", "bedroom"],
    dimensions: '3 panels — 40 x 60 cm each',
    inStock: true,
    imageKey: "wall-decor",
    gallery: ["wall-decor", "room-living", "room-office"],
    tags: ["canvas", "art", "triptych", "neutral", "statement"],
    isBestSeller: true,
    isLuxury: true,
    popularity: 96,
  },
  {
    id: "lh-002",
    name: "Solene Oak Gallery Frame Set",
    category: "wall-decor",
    subcategory: "Photo Frames",
    price: 6900,
    rating: 4.6,
    reviews: 84,
    description:
      "Six slim solid-oak frames in mixed sizes, cut with generous ivory mounts so every photograph is given room to breathe. Hanging template included.",
    material: "Solid oak, museum glass",
    color: "Natural Oak",
    style: "Minimal",
    rooms: ["living", "bedroom", "office"],
    dimensions: "Set of 6 — A4, A5 and 13 x 18 cm",
    inStock: true,
    imageKey: "wall-decor",
    gallery: ["wall-decor", "room-bedroom"],
    tags: ["frames", "gallery wall", "oak", "photos"],
    isNew: true,
    popularity: 78,
  },
  {
    id: "lh-003",
    name: "Meridian Brass Wall Clock",
    category: "wall-decor",
    subcategory: "Wall Clocks",
    price: 8900,
    discount: 10,
    rating: 4.7,
    reviews: 61,
    description:
      "A silent-sweep wall clock with a brushed brass rim and a bone-white dial. No ticking, no clutter — only a thin gold second hand.",
    material: "Brushed brass, glass",
    color: "Muted Gold",
    style: "Classic",
    rooms: ["living", "dining", "office"],
    dimensions: "Ø 40 cm",
    inStock: true,
    imageKey: "wall-decor",
    gallery: ["wall-decor", "room-office"],
    tags: ["clock", "brass", "silent", "gold"],
    popularity: 71,
  },
  {
    id: "lh-004",
    name: "Amber Field Macramé Wall Hanging",
    category: "wall-decor",
    subcategory: "Macramé Wall Hangings",
    price: 4500,
    rating: 4.5,
    reviews: 47,
    description:
      "Hand-knotted in undyed cotton cord on a seasoned teak dowel, finished with a long combed fringe that softens any bare wall.",
    material: "Cotton cord, teak dowel",
    color: "Cream",
    style: "Boho",
    rooms: ["bedroom", "living", "kids"],
    dimensions: "70 x 95 cm",
    inStock: true,
    imageKey: "handmade",
    gallery: ["handmade", "cat-bedroom", "room-bedroom"],
    tags: ["macrame", "handmade", "boho", "cotton", "wall hanging"],
    isHandmade: true,
    popularity: 66,
  },
  {
    id: "lh-005",
    name: "Verse Minimal Wall Quote Decal",
    category: "wall-decor",
    subcategory: "Wall Quotes",
    price: 1499,
    rating: 4.3,
    reviews: 210,
    description:
      "A matte vinyl decal set in a fine serif — 'and breathe' — that reads as painted lettering once applied. Removable, residue-free.",
    material: "Matte vinyl",
    color: "Espresso",
    style: "Minimal",
    rooms: ["bedroom", "office", "bathroom"],
    dimensions: "60 x 18 cm",
    inStock: true,
    imageKey: "wall-decor",
    gallery: ["wall-decor"],
    tags: ["decal", "quote", "sticker", "budget", "typography"],
    popularity: 58,
  },
  {
    id: "lh-006",
    name: "Terra Ribbed 3D Wall Panel Set",
    category: "wall-decor",
    subcategory: "3D Wall Panels",
    price: 12500,
    rating: 4.4,
    reviews: 33,
    description:
      "Twelve fluted panels in a warm bone finish that build a full ribbed feature wall. Paintable, lightweight and simple to install.",
    material: "Bamboo fibre composite",
    color: "Bone",
    style: "Modern",
    rooms: ["living", "bedroom", "entrance"],
    dimensions: "12 panels — 60 x 30 cm each",
    inStock: false,
    imageKey: "wall-decor",
    gallery: ["wall-decor", "room-living"],
    tags: ["panel", "fluted", "feature wall", "texture"],
    popularity: 44,
  },

  // ---------- Showpieces ----------
  {
    id: "lh-007",
    name: "Lune Marble & Brass Sculpture",
    category: "showpieces",
    subcategory: "Abstract Sculptures",
    price: 24999,
    discount: 12,
    rating: 4.9,
    reviews: 58,
    description:
      "A crescent of honed white marble balanced on a polished brass base, finished with a single hand-drawn brass arc. Each piece has its own veining.",
    material: "Marble, solid brass",
    color: "Ivory",
    style: "Luxury",
    rooms: ["living", "entrance", "office"],
    dimensions: "22 x 14 x 28 cm",
    inStock: true,
    imageKey: "showpieces",
    gallery: ["showpieces", "room-living"],
    tags: ["sculpture", "marble", "brass", "statement", "luxury"],
    isLuxury: true,
    isBestSeller: true,
    popularity: 92,
  },
  {
    id: "lh-008",
    name: "Aster Ceramic Bird Pair",
    category: "showpieces",
    subcategory: "Animal Figurines",
    price: 3800,
    rating: 4.5,
    reviews: 92,
    description:
      "Two glazed ceramic birds in cream and sand, shaped in soft geometry. Quietly charming on a console or shelf.",
    material: "Glazed ceramic",
    color: "Cream",
    style: "Minimal",
    rooms: ["living", "bedroom", "entrance"],
    dimensions: "14 cm and 10 cm tall",
    inStock: true,
    imageKey: "showpieces",
    gallery: ["showpieces"],
    tags: ["figurine", "ceramic", "birds", "shelf decor"],
    popularity: 63,
  },
  {
    id: "lh-009",
    name: "Duet Abstract Couple Figurine",
    category: "showpieces",
    subcategory: "Couple Figurines",
    price: 5600,
    rating: 4.6,
    reviews: 74,
    description:
      "Two abstract forms leaning into one another, cast in warm resin with a stone-like finish and a walnut base.",
    material: "Resin, walnut",
    color: "Sand",
    style: "Modern",
    rooms: ["bedroom", "living"],
    dimensions: "18 x 9 x 26 cm",
    inStock: true,
    imageKey: "showpieces",
    gallery: ["showpieces", "room-bedroom"],
    tags: ["figurine", "couple", "gift", "resin"],
    popularity: 69,
  },
  {
    id: "lh-010",
    name: "Orbit Smoked Glass Object",
    category: "showpieces",
    subcategory: "Glass Showpieces",
    price: 7200,
    rating: 4.4,
    reviews: 39,
    description:
      "A hand-blown smoked glass sphere resting in a brushed brass ring — a small, serious object for a coffee table stack.",
    material: "Hand-blown glass, brass",
    color: "Smoke",
    style: "Luxury",
    rooms: ["living", "office"],
    dimensions: "Ø 16 cm",
    inStock: true,
    imageKey: "showpieces",
    gallery: ["showpieces", "shop-the-look"],
    tags: ["glass", "object", "coffee table", "brass"],
    isLuxury: true,
    popularity: 55,
  },

  // ---------- Plants ----------
  {
    id: "lh-011",
    name: "Olivia Faux Olive Tree",
    category: "plants",
    subcategory: "Artificial Plants",
    price: 14500,
    discount: 20,
    rating: 4.8,
    reviews: 148,
    description:
      "A 150 cm faux olive tree with real-touch leaves and natural branch spread, potted in a fibre-clay planter with dressing stones.",
    material: "Real-touch polymer, fibre clay pot",
    color: "Green",
    style: "Mediterranean",
    rooms: ["living", "entrance", "office"],
    dimensions: "150 cm tall, Ø 32 cm pot",
    inStock: true,
    imageKey: "plants",
    gallery: ["plants", "room-living"],
    tags: ["plant", "olive", "faux", "greenery", "statement"],
    isBestSeller: true,
    popularity: 94,
  },
  {
    id: "lh-012",
    name: "Petit Succulent Trio in Stone Pots",
    category: "plants",
    subcategory: "Succulents",
    price: 2999,
    rating: 4.4,
    reviews: 118,
    description:
      "Three miniature succulents in speckled stoneware pots — the easiest way to soften a desk, ledge or bathroom shelf.",
    material: "Polymer foliage, stoneware",
    color: "Sage",
    style: "Minimal",
    rooms: ["office", "bathroom", "bedroom"],
    dimensions: "12 cm tall each",
    inStock: true,
    imageKey: "plants",
    gallery: ["plants", "room-office"],
    tags: ["succulent", "mini", "desk", "budget"],
    popularity: 61,
  },
  {
    id: "lh-013",
    name: "Cascade Hanging Ivy Planter",
    category: "plants",
    subcategory: "Hanging Plants",
    price: 4200,
    rating: 4.3,
    reviews: 56,
    description:
      "Trailing faux ivy in a hand-woven jute hanger, dense enough to read as real from across the room.",
    material: "Polyester foliage, jute rope",
    color: "Green",
    style: "Boho",
    rooms: ["balcony", "living", "bathroom"],
    dimensions: "90 cm drop",
    inStock: true,
    imageKey: "plants",
    gallery: ["plants", "outdoor"],
    tags: ["hanging", "ivy", "jute", "balcony"],
    popularity: 49,
  },
  {
    id: "lh-014",
    name: "Kaya Fluted Ceramic Planter",
    category: "plants",
    subcategory: "Decorative Plant Pots",
    price: 5400,
    rating: 4.6,
    reviews: 71,
    description:
      "A generously fluted planter glazed in warm chalk white, with a concealed drainage insert and felted base.",
    material: "Glazed ceramic",
    color: "Chalk",
    style: "Modern",
    rooms: ["living", "balcony", "entrance"],
    dimensions: "Ø 28 x 26 cm",
    inStock: true,
    imageKey: "plants",
    gallery: ["plants", "room-entrance"],
    tags: ["planter", "ceramic", "fluted", "pot"],
    popularity: 57,
  },

  // ---------- Lighting ----------
  {
    id: "lh-015",
    name: "Halo Brass Dome Table Lamp",
    category: "lighting",
    subcategory: "Table Lamps",
    price: 21500,
    discount: 10,
    rating: 4.9,
    reviews: 103,
    description:
      "A solid brass dome shade on a slim stem, throwing a warm pool of light downward. Dimmable, with a fabric braided cord.",
    material: "Solid brass",
    color: "Muted Gold",
    style: "Luxury",
    rooms: ["living", "bedroom", "office"],
    dimensions: "Ø 26 x 48 cm",
    inStock: true,
    imageKey: "lighting",
    gallery: ["lighting", "shop-the-look"],
    tags: ["lamp", "brass", "dimmable", "warm light", "luxury"],
    isLuxury: true,
    isBestSeller: true,
    popularity: 98,
  },
  {
    id: "lh-016",
    name: "Lin Linen Shade Bedside Lamp",
    category: "lighting",
    subcategory: "Bedside Lamps",
    price: 9800,
    rating: 4.6,
    reviews: 88,
    description:
      "An antique-brass base with a hand-tailored ivory linen shade — soft, even light for reading at the end of the day.",
    material: "Brass, linen",
    color: "Ivory",
    style: "Classic",
    rooms: ["bedroom", "living"],
    dimensions: "Ø 22 x 42 cm",
    inStock: true,
    imageKey: "lighting",
    gallery: ["lighting", "room-bedroom"],
    tags: ["lamp", "bedside", "linen", "reading"],
    popularity: 74,
  },
  {
    id: "lh-017",
    name: "Aurel Warm Fairy Light Curtain",
    category: "lighting",
    subcategory: "Fairy Lights",
    price: 2499,
    discount: 20,
    rating: 4.4,
    reviews: 240,
    description:
      "Ten metres of copper-wire fairy lights in a 2700K warm glow, with eight modes and a memory timer. Indoor and covered-balcony safe.",
    material: "Copper wire, LED",
    color: "Warm White",
    style: "Modern",
    rooms: ["bedroom", "balcony", "kids"],
    dimensions: "10 m, 100 LEDs",
    inStock: true,
    imageKey: "lighting",
    gallery: ["lighting", "outdoor"],
    tags: ["fairy lights", "led", "string lights", "budget", "festive"],
    popularity: 81,
  },
  {
    id: "lh-018",
    name: "Noor Pierced Brass Lantern",
    category: "lighting",
    subcategory: "Lanterns",
    price: 7500,
    rating: 4.7,
    reviews: 66,
    description:
      "A hand-pierced brass lantern that casts fine geometric shadows across a wall. Takes a pillar candle or LED insert.",
    material: "Pierced brass",
    color: "Antique Brass",
    style: "Traditional",
    rooms: ["living", "balcony", "entrance"],
    dimensions: "18 x 18 x 40 cm",
    inStock: true,
    imageKey: "islamic",
    gallery: ["islamic", "outdoor"],
    tags: ["lantern", "brass", "ramadan", "candle", "shadow"],
    isHandmade: true,
    popularity: 76,
  },
  {
    id: "lh-019",
    name: "Lueur Custom Script Neon Sign",
    category: "lighting",
    subcategory: "Neon Signs",
    price: 16500,
    rating: 4.5,
    reviews: 42,
    description:
      "A warm-white flexible LED neon sign in a fine script, mounted on clear acrylic. Personalise the wording at checkout notes.",
    material: "Flexible LED, acrylic",
    color: "Warm White",
    style: "Modern",
    rooms: ["living", "bedroom", "office"],
    dimensions: "Up to 80 x 30 cm",
    inStock: true,
    imageKey: "personalized",
    gallery: ["personalized", "lighting"],
    tags: ["neon", "custom", "personalised", "led", "sign"],
    popularity: 59,
  },

  // ---------- Candles ----------
  {
    id: "lh-020",
    name: "Maison Amber Oud Scented Candle",
    category: "candles",
    subcategory: "Scented Candles",
    price: 4800,
    discount: 15,
    rating: 4.8,
    reviews: 176,
    description:
      "Amber, oud and a trace of cedar in a ribbed ceramic vessel with a cotton wick. Fifty hours of burn time, and a vessel worth keeping.",
    material: "Soy wax, ceramic",
    color: "Sand",
    style: "Luxury",
    rooms: ["living", "bedroom", "bathroom"],
    dimensions: "Ø 9 x 10 cm, 280 g",
    inStock: true,
    imageKey: "candles",
    gallery: ["candles", "room-bathroom"],
    tags: ["candle", "scented", "oud", "amber", "gift"],
    isBestSeller: true,
    isLuxury: true,
    popularity: 95,
  },
  {
    id: "lh-021",
    name: "Fig & Fresia Reed Diffuser",
    category: "candles",
    subcategory: "Reed Diffusers",
    price: 5200,
    rating: 4.6,
    reviews: 97,
    description:
      "A fluted glass bottle with a brass collar and natural rattan reeds. Green fig softened with freesia — steady scent for twelve weeks.",
    material: "Glass, brass, rattan",
    color: "Ivory",
    style: "Modern",
    rooms: ["bathroom", "entrance", "living"],
    dimensions: "200 ml",
    inStock: true,
    imageKey: "candles",
    gallery: ["candles"],
    tags: ["diffuser", "fragrance", "reed", "fig"],
    popularity: 72,
  },
  {
    id: "lh-022",
    name: "Cinq Brass Tealight Holder Set",
    category: "candles",
    subcategory: "Tealight Holders",
    price: 3600,
    rating: 4.5,
    reviews: 64,
    description:
      "Five turned brass tealight holders at graduated heights — a complete centrepiece on their own.",
    material: "Solid brass",
    color: "Muted Gold",
    style: "Classic",
    rooms: ["dining", "living"],
    dimensions: "Heights 6 – 16 cm",
    inStock: true,
    imageKey: "tabletop",
    gallery: ["tabletop", "room-dining"],
    tags: ["tealight", "brass", "candle holder", "centerpiece"],
    popularity: 62,
  },
  {
    id: "lh-023",
    name: "Nuit Pillar Candle Collection",
    category: "candles",
    subcategory: "Candle Sets",
    price: 3200,
    rating: 4.3,
    reviews: 51,
    description:
      "Six unscented ivory pillar candles in three heights, poured from clean-burning soy wax with a smokeless wick.",
    material: "Soy wax",
    color: "Ivory",
    style: "Minimal",
    rooms: ["dining", "living", "bedroom"],
    dimensions: "Set of 6 — 10, 15, 20 cm",
    inStock: true,
    imageKey: "candles",
    gallery: ["candles", "room-dining"],
    tags: ["candles", "pillar", "set", "unscented"],
    popularity: 53,
  },

  // ---------- Mirrors ----------
  {
    id: "lh-024",
    name: "Arcadia Arched Brass Mirror",
    category: "mirrors",
    subcategory: "Arched Mirrors",
    price: 32500,
    discount: 10,
    rating: 4.9,
    reviews: 87,
    description:
      "A full-height arched mirror in a slim brushed-brass frame. Lean it against a wall or fix it — either way it doubles the light.",
    material: "Brushed brass, 5 mm glass",
    color: "Muted Gold",
    style: "Luxury",
    rooms: ["entrance", "bedroom", "living"],
    dimensions: "90 x 170 cm",
    inStock: true,
    imageKey: "mirrors",
    gallery: ["mirrors", "room-entrance"],
    tags: ["mirror", "arched", "brass", "full length", "luxury"],
    isLuxury: true,
    isBestSeller: true,
    popularity: 97,
  },
  {
    id: "lh-025",
    name: "Sol Round Gold Rim Mirror",
    category: "mirrors",
    subcategory: "Round Mirrors",
    price: 11900,
    rating: 4.7,
    reviews: 112,
    description:
      "A perfectly circular mirror with a fine gold rim — the quiet fix for a bathroom or entry wall.",
    material: "Metal frame, glass",
    color: "Muted Gold",
    style: "Minimal",
    rooms: ["bathroom", "entrance", "bedroom"],
    dimensions: "Ø 70 cm",
    inStock: true,
    imageKey: "mirrors",
    gallery: ["mirrors", "room-bathroom"],
    tags: ["mirror", "round", "gold", "bathroom"],
    popularity: 84,
  },
  {
    id: "lh-026",
    name: "Prism Geometric Mirror Cluster",
    category: "mirrors",
    subcategory: "Geometric Mirrors",
    price: 8400,
    rating: 4.4,
    reviews: 38,
    description:
      "Seven hexagonal mirrors with bevelled edges, arranged as a honeycomb or scattered across a wall.",
    material: "Bevelled glass, MDF backing",
    color: "Clear",
    style: "Modern",
    rooms: ["living", "office", "entrance"],
    dimensions: "Set of 7 — 20 cm each",
    inStock: true,
    imageKey: "mirrors",
    gallery: ["mirrors"],
    tags: ["mirror", "geometric", "hexagon", "cluster"],
    popularity: 48,
  },

  // ---------- Rugs ----------
  {
    id: "lh-027",
    name: "Saha Hand-Knotted Wool Rug",
    category: "rugs",
    subcategory: "Area Rugs",
    price: 68000,
    discount: 15,
    rating: 4.9,
    reviews: 44,
    description:
      "Hand-knotted in Lahore from undyed highland wool, with a subtle charcoal diamond field. A generational rug, not a seasonal one.",
    material: "100% wool",
    color: "Beige",
    style: "Traditional",
    rooms: ["living", "bedroom"],
    dimensions: "170 x 240 cm",
    inStock: true,
    imageKey: "rugs",
    gallery: ["rugs", "room-living"],
    tags: ["rug", "wool", "hand-knotted", "luxury", "area rug"],
    isLuxury: true,
    isHandmade: true,
    popularity: 88,
  },
  {
    id: "lh-028",
    name: "Halka Round Jute Rug",
    category: "rugs",
    subcategory: "Round Rugs",
    price: 12500,
    rating: 4.5,
    reviews: 69,
    description:
      "A flat-braided jute round with a natural slub, grounding a reading corner or a child's room without visual weight.",
    material: "Natural jute",
    color: "Natural",
    style: "Boho",
    rooms: ["living", "kids", "balcony"],
    dimensions: "Ø 150 cm",
    inStock: true,
    imageKey: "rugs",
    gallery: ["rugs", "room-kids"],
    tags: ["rug", "jute", "round", "natural"],
    popularity: 64,
  },
  {
    id: "lh-029",
    name: "Corso Woven Runner Rug",
    category: "rugs",
    subcategory: "Runner Rugs",
    price: 9500,
    rating: 4.4,
    reviews: 41,
    description:
      "A low-pile runner in espresso and sand, sized for a hallway and finished with a hand-bound edge.",
    material: "Wool blend",
    color: "Espresso",
    style: "Modern",
    rooms: ["entrance", "bedroom"],
    dimensions: "80 x 240 cm",
    inStock: true,
    imageKey: "rugs",
    gallery: ["rugs", "room-entrance"],
    tags: ["runner", "hallway", "rug", "low pile"],
    popularity: 51,
  },
  {
    id: "lh-030",
    name: "Duna Boucle Floor Pouf",
    category: "rugs",
    subcategory: "Poufs",
    price: 14900,
    rating: 4.6,
    reviews: 35,
    description:
      "A firm cylindrical pouf upholstered in cream boucle — extra seating that reads as sculpture when unused.",
    material: "Boucle, foam fill",
    color: "Cream",
    style: "Modern",
    rooms: ["living", "bedroom"],
    dimensions: "Ø 50 x 40 cm",
    inStock: true,
    imageKey: "soft-decor",
    gallery: ["soft-decor", "room-living"],
    tags: ["pouf", "boucle", "seating", "floor"],
    popularity: 47,
  },

  // ---------- Soft Decor ----------
  {
    id: "lh-031",
    name: "Ravel Linen Cushion Cover Set",
    category: "soft-decor",
    subcategory: "Cushion Covers",
    price: 5800,
    discount: 20,
    rating: 4.7,
    reviews: 158,
    description:
      "Four washed-linen covers in ivory, oat, sand and espresso, with concealed zips and a soft, lived-in handle from the first wash.",
    material: "Washed linen",
    color: "Mixed Neutrals",
    style: "Minimal",
    rooms: ["living", "bedroom"],
    dimensions: "Set of 4 — 45 x 45 cm",
    inStock: true,
    imageKey: "soft-decor",
    gallery: ["soft-decor", "room-living"],
    tags: ["cushion", "linen", "covers", "neutral", "set"],
    isBestSeller: true,
    popularity: 90,
  },
  {
    id: "lh-032",
    name: "Meso Chunky Knit Throw",
    category: "soft-decor",
    subcategory: "Decorative Throws",
    price: 8900,
    rating: 4.8,
    reviews: 121,
    description:
      "A heavy waffle-knit throw in warm oat with a hand-tied fringe. Weighty enough to stay where you drape it.",
    material: "Cotton-acrylic blend",
    color: "Oat",
    style: "Cozy",
    rooms: ["living", "bedroom"],
    dimensions: "130 x 170 cm",
    inStock: true,
    imageKey: "soft-decor",
    gallery: ["soft-decor", "room-bedroom"],
    tags: ["throw", "knit", "blanket", "cozy"],
    isBestSeller: true,
    popularity: 86,
  },
  {
    id: "lh-033",
    name: "Velour Emerald Bolster Cover",
    category: "soft-decor",
    subcategory: "Bolster Covers",
    price: 3400,
    rating: 4.3,
    reviews: 29,
    description:
      "A deep emerald cotton-velvet bolster cover with piped ends — one considered accent against a neutral scheme.",
    material: "Cotton velvet",
    color: "Emerald",
    style: "Luxury",
    rooms: ["living", "bedroom"],
    dimensions: "50 x 20 cm",
    inStock: true,
    imageKey: "soft-decor",
    gallery: ["soft-decor"],
    tags: ["bolster", "velvet", "emerald", "accent"],
    popularity: 40,
  },

  // ---------- Curtains ----------
  {
    id: "lh-034",
    name: "Voile Sheer Linen Curtain Pair",
    category: "curtains",
    subcategory: "Sheer Curtains",
    price: 11500,
    discount: 10,
    rating: 4.6,
    reviews: 93,
    description:
      "Floor-length sheer linen panels that turn hard afternoon sun into a soft ivory wash. Sold as a pair with hidden tab tops.",
    material: "Linen voile",
    color: "Ivory",
    style: "Minimal",
    rooms: ["living", "bedroom"],
    dimensions: "Pair — 140 x 270 cm each",
    inStock: true,
    imageKey: "curtains",
    gallery: ["curtains", "room-bedroom"],
    tags: ["curtains", "sheer", "linen", "window"],
    isBestSeller: true,
    popularity: 79,
  },
  {
    id: "lh-035",
    name: "Ombre Blackout Curtain Pair",
    category: "curtains",
    subcategory: "Curtains",
    price: 16800,
    rating: 4.5,
    reviews: 58,
    description:
      "A triple-weave blackout curtain in warm taupe with a matte finish, blocking light and dulling street noise.",
    material: "Triple-weave polyester",
    color: "Taupe",
    style: "Modern",
    rooms: ["bedroom", "living"],
    dimensions: "Pair — 140 x 270 cm each",
    inStock: true,
    imageKey: "curtains",
    gallery: ["curtains"],
    tags: ["curtains", "blackout", "bedroom", "taupe"],
    popularity: 60,
  },
  {
    id: "lh-036",
    name: "Anneau Brass Curtain Tieback Pair",
    category: "curtains",
    subcategory: "Curtain Tiebacks",
    price: 2400,
    rating: 4.2,
    reviews: 31,
    description:
      "Two cast-brass ring tiebacks with a leather strap — a small upgrade that changes how a whole window reads.",
    material: "Cast brass, leather",
    color: "Antique Brass",
    style: "Classic",
    rooms: ["living", "bedroom"],
    dimensions: "Ø 12 cm",
    inStock: true,
    imageKey: "curtains",
    gallery: ["curtains"],
    tags: ["tieback", "brass", "curtain", "hardware"],
    popularity: 36,
  },

  // ---------- Vases ----------
  {
    id: "lh-037",
    name: "Anse Sculptural Ceramic Vase",
    category: "vases",
    subcategory: "Ceramic Vases",
    price: 9600,
    rating: 4.8,
    reviews: 106,
    description:
      "A curved matte-glaze vase with a carved aperture, designed to look complete with a single branch or nothing at all.",
    material: "Matte-glazed stoneware",
    color: "Cream",
    style: "Modern",
    rooms: ["living", "dining", "entrance"],
    dimensions: "Ø 24 x 28 cm",
    inStock: true,
    imageKey: "vases",
    gallery: ["vases", "shop-the-look"],
    tags: ["vase", "ceramic", "sculptural", "centerpiece"],
    isBestSeller: true,
    popularity: 91,
  },
  {
    id: "lh-038",
    name: "Fumé Smoked Glass Vase",
    category: "vases",
    subcategory: "Glass Vases",
    price: 6400,
    rating: 4.5,
    reviews: 62,
    description:
      "Hand-blown in a warm smoke tone with a narrow neck that holds stems upright without a frog.",
    material: "Hand-blown glass",
    color: "Smoke",
    style: "Luxury",
    rooms: ["living", "dining"],
    dimensions: "Ø 14 x 30 cm",
    inStock: true,
    imageKey: "vases",
    gallery: ["vases"],
    tags: ["vase", "glass", "smoked", "flowers"],
    isLuxury: true,
    popularity: 66,
  },
  {
    id: "lh-039",
    name: "Bassin Travertine Decorative Bowl",
    category: "vases",
    subcategory: "Decorative Bowls",
    price: 13500,
    discount: 12,
    rating: 4.7,
    reviews: 48,
    description:
      "Turned from a single block of travertine, with the stone's natural pitting left visible. Weighty and cool to the touch.",
    material: "Travertine",
    color: "Sand",
    style: "Luxury",
    rooms: ["living", "dining", "entrance"],
    dimensions: "Ø 32 x 9 cm",
    inStock: true,
    imageKey: "vases",
    gallery: ["vases", "tabletop"],
    tags: ["bowl", "travertine", "stone", "coffee table"],
    isLuxury: true,
    popularity: 70,
  },
  {
    id: "lh-040",
    name: "Colonne Tall Floor Vase",
    category: "vases",
    subcategory: "Floor Vases",
    price: 17500,
    rating: 4.6,
    reviews: 33,
    description:
      "A 70 cm terracotta floor vase in a chalky limewash finish — built for pampas, branches or standing alone in a corner.",
    material: "Terracotta, limewash",
    color: "Chalk",
    style: "Mediterranean",
    rooms: ["living", "entrance"],
    dimensions: "Ø 30 x 70 cm",
    inStock: true,
    imageKey: "vases",
    gallery: ["vases", "room-living"],
    tags: ["floor vase", "terracotta", "tall", "pampas"],
    popularity: 58,
  },

  // ---------- Storage ----------
  {
    id: "lh-041",
    name: "Sana Woven Seagrass Basket Set",
    category: "storage",
    subcategory: "Storage Baskets",
    price: 7800,
    discount: 15,
    rating: 4.6,
    reviews: 88,
    description:
      "Three hand-woven seagrass baskets in nesting sizes, with soft rolled handles and a stiffened base that holds its shape.",
    material: "Seagrass",
    color: "Natural",
    style: "Boho",
    rooms: ["living", "bedroom", "kids"],
    dimensions: "Set of 3 — Ø 40, 32, 24 cm",
    inStock: true,
    imageKey: "storage",
    gallery: ["storage", "room-kids"],
    tags: ["basket", "seagrass", "storage", "handmade", "set"],
    isHandmade: true,
    popularity: 77,
  },
  {
    id: "lh-042",
    name: "Écrin Velvet Jewellery Box",
    category: "storage",
    subcategory: "Jewelry Boxes",
    price: 6200,
    rating: 4.7,
    reviews: 54,
    description:
      "A lacquered box lined in champagne velvet, with a ring roll, a lifting tray and a soft-close brass hinge.",
    material: "Lacquered wood, velvet",
    color: "Champagne",
    style: "Luxury",
    rooms: ["bedroom"],
    dimensions: "24 x 16 x 10 cm",
    inStock: true,
    imageKey: "storage",
    gallery: ["storage", "room-bedroom"],
    tags: ["jewellery box", "velvet", "gift", "storage"],
    isLuxury: true,
    popularity: 65,
  },
  {
    id: "lh-043",
    name: "Clef Brass Wall Key Holder",
    category: "storage",
    subcategory: "Key Holders",
    price: 2800,
    rating: 4.3,
    reviews: 76,
    description:
      "A slim walnut bar with five turned brass hooks and a concealed mounting plate — no visible screws.",
    material: "Walnut, brass",
    color: "Walnut",
    style: "Minimal",
    rooms: ["entrance"],
    dimensions: "36 x 6 cm",
    inStock: true,
    imageKey: "entryway",
    gallery: ["entryway", "room-entrance"],
    tags: ["key holder", "entryway", "brass", "walnut"],
    popularity: 52,
  },
  {
    id: "lh-044",
    name: "Ordre Ceramic Desk Organizer",
    category: "storage",
    subcategory: "Desk Organizers",
    price: 4100,
    rating: 4.4,
    reviews: 43,
    description:
      "A three-well ceramic caddy in bone glaze for pens, clips and the small things that clutter a desk.",
    material: "Glazed ceramic",
    color: "Bone",
    style: "Minimal",
    rooms: ["office"],
    dimensions: "22 x 10 x 11 cm",
    inStock: true,
    imageKey: "storage",
    gallery: ["storage", "room-office"],
    tags: ["organizer", "desk", "ceramic", "office"],
    popularity: 42,
  },

  // ---------- Tabletop ----------
  {
    id: "lh-045",
    name: "Trame Linen Table Runner",
    category: "tabletop",
    subcategory: "Table Runners",
    price: 4600,
    rating: 4.5,
    reviews: 67,
    description:
      "A slub-linen runner in warm ivory with hand-knotted fringe ends, long enough to overhang a six-seater.",
    material: "Slub linen",
    color: "Ivory",
    style: "Minimal",
    rooms: ["dining"],
    dimensions: "40 x 220 cm",
    inStock: true,
    imageKey: "tabletop",
    gallery: ["tabletop", "room-dining"],
    tags: ["runner", "linen", "dining", "table"],
    popularity: 61,
  },
  {
    id: "lh-046",
    name: "Pierre Marble Coaster Set",
    category: "tabletop",
    subcategory: "Coasters",
    price: 3900,
    rating: 4.6,
    reviews: 82,
    description:
      "Six honed marble coasters with brushed gold edging and a felt underside that won't scratch a table.",
    material: "Marble, brass edging",
    color: "White Marble",
    style: "Luxury",
    rooms: ["living", "dining"],
    dimensions: "Set of 6 — Ø 10 cm",
    inStock: true,
    imageKey: "tabletop",
    gallery: ["tabletop"],
    tags: ["coasters", "marble", "gold", "set", "gift"],
    isLuxury: true,
    popularity: 68,
  },
  {
    id: "lh-047",
    name: "Cercle Hammered Brass Centerpiece Bowl",
    category: "tabletop",
    subcategory: "Centerpieces",
    price: 10500,
    discount: 10,
    rating: 4.7,
    reviews: 46,
    description:
      "A wide hammered-brass bowl with a warm antique patina — fruit, potpourri or nothing at all.",
    material: "Hammered brass",
    color: "Muted Gold",
    style: "Traditional",
    rooms: ["dining", "living"],
    dimensions: "Ø 36 x 12 cm",
    inStock: true,
    imageKey: "tabletop",
    gallery: ["tabletop", "room-dining"],
    tags: ["centerpiece", "brass", "bowl", "dining"],
    isHandmade: true,
    popularity: 63,
  },

  // ---------- Entryway ----------
  {
    id: "lh-048",
    name: "Bienvenue Eucalyptus Door Wreath",
    category: "entryway",
    subcategory: "Wreaths",
    price: 5900,
    rating: 4.6,
    reviews: 57,
    description:
      "Preserved eucalyptus bound onto a natural vine base, holding its silver-green colour for years indoors.",
    material: "Preserved eucalyptus, vine",
    color: "Sage",
    style: "Natural",
    rooms: ["entrance"],
    dimensions: "Ø 45 cm",
    inStock: true,
    imageKey: "entryway",
    gallery: ["entryway"],
    tags: ["wreath", "door", "eucalyptus", "entryway"],
    isHandmade: true,
    popularity: 59,
  },
  {
    id: "lh-049",
    name: "Seuil Coir Patterned Doormat",
    category: "entryway",
    subcategory: "Doormats",
    price: 2600,
    rating: 4.3,
    reviews: 94,
    description:
      "Thick natural coir with a screen-printed geometric border and a non-slip vinyl backing.",
    material: "Coir, vinyl backing",
    color: "Natural",
    style: "Modern",
    rooms: ["entrance", "balcony"],
    dimensions: "45 x 75 cm",
    inStock: true,
    imageKey: "entryway",
    gallery: ["entryway", "room-entrance"],
    tags: ["doormat", "coir", "entryway", "budget"],
    popularity: 55,
  },

  // ---------- Kids ----------
  {
    id: "lh-050",
    name: "Nuage Cloud Night Light",
    category: "kids",
    subcategory: "Night Lights",
    price: 4400,
    rating: 4.7,
    reviews: 103,
    description:
      "A soft silicone cloud lamp with three warm brightness levels, a touch switch and a rechargeable battery.",
    material: "Food-grade silicone",
    color: "Ivory",
    style: "Playful",
    rooms: ["kids", "bedroom"],
    dimensions: "22 x 14 cm",
    inStock: true,
    imageKey: "kids",
    gallery: ["kids", "room-kids"],
    tags: ["night light", "kids", "cloud", "rechargeable"],
    popularity: 73,
  },
  {
    id: "lh-051",
    name: "Rêve Cotton Dream Catcher",
    category: "kids",
    subcategory: "Dream Catchers",
    price: 3100,
    rating: 4.4,
    reviews: 49,
    description:
      "Hand-woven in natural cotton with wooden beads and a long feathered tail, in a calm undyed palette.",
    material: "Cotton, wood beads",
    color: "Cream",
    style: "Boho",
    rooms: ["kids", "bedroom"],
    dimensions: "Ø 30 x 80 cm drop",
    inStock: true,
    imageKey: "kids",
    gallery: ["kids"],
    tags: ["dream catcher", "kids", "handmade", "cotton"],
    isHandmade: true,
    popularity: 45,
  },
  {
    id: "lh-052",
    name: "Alphabet Wooden Name Letters",
    category: "kids",
    subcategory: "Name Signs",
    price: 3800,
    rating: 4.5,
    reviews: 61,
    description:
      "Chunky beech letters with rounded edges, sanded smooth and finished in a clear child-safe oil. Choose any name.",
    material: "Beech wood",
    color: "Natural Wood",
    style: "Playful",
    rooms: ["kids"],
    dimensions: "12 cm tall per letter",
    inStock: true,
    imageKey: "kids",
    gallery: ["kids", "room-kids"],
    tags: ["name", "letters", "wood", "personalised", "kids"],
    popularity: 50,
  },

  // ---------- Outdoor ----------
  {
    id: "lh-053",
    name: "Terrasse Solar String Lights",
    category: "outdoor",
    subcategory: "Solar Lights",
    price: 6800,
    discount: 15,
    rating: 4.6,
    reviews: 112,
    description:
      "Fifteen metres of weatherproof S14 bulbs on a solar panel with a USB backup — warm, steady light for a balcony all evening.",
    material: "Shatterproof PC bulbs",
    color: "Warm White",
    style: "Modern",
    rooms: ["balcony", "entrance"],
    dimensions: "15 m, 25 bulbs",
    inStock: true,
    imageKey: "outdoor",
    gallery: ["outdoor"],
    tags: ["solar", "string lights", "balcony", "outdoor", "weatherproof"],
    isBestSeller: true,
    popularity: 82,
  },
  {
    id: "lh-054",
    name: "Vent Bamboo Wind Chime",
    category: "outdoor",
    subcategory: "Wind Chimes",
    price: 2900,
    rating: 4.2,
    reviews: 37,
    description:
      "Six tuned bamboo tubes on a cotton cord — a low, hollow tone rather than a bright metallic one.",
    material: "Bamboo, cotton cord",
    color: "Natural",
    style: "Natural",
    rooms: ["balcony", "entrance"],
    dimensions: "70 cm drop",
    inStock: true,
    imageKey: "outdoor",
    gallery: ["outdoor"],
    tags: ["wind chime", "bamboo", "balcony", "outdoor"],
    popularity: 38,
  },
  {
    id: "lh-055",
    name: "Argile Terracotta Planter Trio",
    category: "outdoor",
    subcategory: "Decorative Pots",
    price: 7400,
    rating: 4.5,
    reviews: 52,
    description:
      "Three unglazed terracotta pots with matching saucers, frost-safe and breathable for balcony planting.",
    material: "Terracotta",
    color: "Terracotta",
    style: "Mediterranean",
    rooms: ["balcony"],
    dimensions: "Ø 30, 24, 18 cm",
    inStock: true,
    imageKey: "outdoor",
    gallery: ["outdoor", "plants"],
    tags: ["planter", "terracotta", "balcony", "pots", "set"],
    popularity: 46,
  },

  // ---------- DIY ----------
  {
    id: "lh-056",
    name: "Atelier Abstract Paint Kit",
    category: "diy",
    subcategory: "Paint Kits",
    price: 5500,
    rating: 4.3,
    reviews: 40,
    description:
      "A complete kit for one large canvas: primed 50 x 70 cm canvas, six neutral acrylics, three brushes and a guided colour card.",
    material: "Canvas, acrylic paint",
    color: "Mixed Neutrals",
    style: "Modern",
    rooms: ["living", "office", "kids"],
    dimensions: "Canvas 50 x 70 cm",
    inStock: true,
    imageKey: "diy",
    gallery: ["diy", "wall-decor"],
    tags: ["diy", "paint", "kit", "craft", "art"],
    popularity: 41,
  },
  {
    id: "lh-057",
    name: "Cirage Candle-Making Kit",
    category: "diy",
    subcategory: "Candle-Making Kits",
    price: 6300,
    rating: 4.4,
    reviews: 34,
    description:
      "Soy wax flakes, three fragrance oils, cotton wicks and four ribbed ceramic vessels — enough for four full-size candles.",
    material: "Soy wax, ceramic",
    color: "Ivory",
    style: "Minimal",
    rooms: ["living", "bedroom"],
    dimensions: "Makes 4 x 180 g candles",
    inStock: true,
    imageKey: "diy",
    gallery: ["diy", "candles"],
    tags: ["diy", "candle", "kit", "craft", "gift"],
    popularity: 43,
  },

  // ---------- Personalized ----------
  {
    id: "lh-058",
    name: "Héritage Engraved Family Name Plaque",
    category: "personalized",
    subcategory: "Family Name Signs",
    price: 9900,
    discount: 10,
    rating: 4.8,
    reviews: 71,
    description:
      "Deep-engraved in solid walnut with a bevelled border and an oiled finish. Your family name, set in a fine classical serif.",
    material: "Solid walnut",
    color: "Walnut",
    style: "Classic",
    rooms: ["entrance", "living"],
    dimensions: "45 x 20 cm",
    inStock: true,
    imageKey: "personalized",
    gallery: ["personalized", "room-entrance"],
    tags: ["personalised", "name", "walnut", "engraved", "family"],
    isBestSeller: true,
    isHandmade: true,
    popularity: 85,
  },
  {
    id: "lh-059",
    name: "Signature Brass Script Wall Word",
    category: "personalized",
    subcategory: "Custom Wall Art",
    price: 7600,
    rating: 4.6,
    reviews: 38,
    description:
      "A single word of your choosing, laser-cut from brushed brass in a flowing script and mounted to float off the wall.",
    material: "Brushed brass",
    color: "Muted Gold",
    style: "Modern",
    rooms: ["living", "bedroom", "entrance"],
    dimensions: "Up to 60 cm wide",
    inStock: true,
    imageKey: "personalized",
    gallery: ["personalized"],
    tags: ["personalised", "brass", "script", "custom", "wall art"],
    popularity: 56,
  },
  {
    id: "lh-060",
    name: "Deux Embroidered Couple Cushion",
    category: "personalized",
    subcategory: "Personalized Cushions",
    price: 4900,
    rating: 4.4,
    reviews: 45,
    description:
      "Two names and a date, hand-embroidered in champagne thread on a heavyweight ivory linen cushion.",
    material: "Linen, cotton thread",
    color: "Ivory",
    style: "Classic",
    rooms: ["bedroom", "living"],
    dimensions: "45 x 45 cm",
    inStock: true,
    imageKey: "soft-decor",
    gallery: ["soft-decor", "personalized"],
    tags: ["personalised", "cushion", "embroidered", "couple", "gift"],
    isHandmade: true,
    popularity: 48,
  },

  // ---------- Festive ----------
  {
    id: "lh-061",
    name: "Hilal Ramadan Lantern Set",
    category: "festive",
    subcategory: "Ramadan Decor",
    price: 12800,
    discount: 15,
    rating: 4.8,
    reviews: 84,
    description:
      "Three pierced metal lanterns in graduated heights with a warm antique-gold finish and flameless LED candles included.",
    material: "Pierced metal, LED",
    color: "Antique Gold",
    style: "Traditional",
    rooms: ["living", "dining", "entrance"],
    dimensions: "Heights 25, 35, 45 cm",
    inStock: true,
    imageKey: "festive",
    gallery: ["festive", "islamic"],
    tags: ["ramadan", "eid", "lantern", "festive", "set"],
    isBestSeller: true,
    popularity: 87,
  },
  {
    id: "lh-062",
    name: "Fête Ivory & Gold Party Banner",
    category: "festive",
    subcategory: "Decorative Banners",
    price: 1899,
    rating: 4.2,
    reviews: 66,
    description:
      "A reusable felt and brushed-foil banner in ivory and muted gold — celebratory without the plastic shine.",
    material: "Felt, brushed foil",
    color: "Ivory",
    style: "Modern",
    rooms: ["living", "dining", "kids"],
    dimensions: "3 m garland",
    inStock: true,
    imageKey: "festive",
    gallery: ["festive"],
    tags: ["banner", "birthday", "festive", "budget", "party"],
    popularity: 39,
  },
  {
    id: "lh-063",
    name: "Nikah Wedding Table Decor Set",
    category: "festive",
    subcategory: "Wedding Decor",
    price: 22500,
    rating: 4.7,
    reviews: 27,
    description:
      "A complete top-table set: two brass candelabras, six votives, a runner and preserved florals in ivory and champagne.",
    material: "Brass, linen, preserved florals",
    color: "Champagne",
    style: "Luxury",
    rooms: ["dining", "living"],
    dimensions: "Set for a 2.4 m table",
    inStock: true,
    imageKey: "festive",
    gallery: ["festive", "room-dining"],
    tags: ["wedding", "festive", "brass", "luxury", "set"],
    isLuxury: true,
    popularity: 54,
  },

  // ---------- Islamic ----------
  {
    id: "lh-064",
    name: "Ayat Al-Kursi Gold Frame",
    category: "islamic",
    subcategory: "Ayat Frames",
    price: 15900,
    discount: 10,
    rating: 4.9,
    reviews: 132,
    description:
      "Ayat al-Kursi rendered in classical Thuluth calligraphy, screen-printed in soft grey on cotton rag paper and framed in slim brushed gold.",
    material: "Cotton rag paper, brass frame",
    color: "Muted Gold",
    style: "Traditional",
    rooms: ["living", "entrance", "bedroom"],
    dimensions: "60 x 80 cm",
    inStock: true,
    imageKey: "islamic",
    gallery: ["islamic", "room-living"],
    tags: ["islamic", "calligraphy", "ayat", "frame", "quran"],
    isBestSeller: true,
    isLuxury: true,
    popularity: 93,
  },
  {
    id: "lh-065",
    name: "Girih Geometric Wall Panel",
    category: "islamic",
    subcategory: "Islamic Geometric Art",
    price: 11200,
    rating: 4.6,
    reviews: 44,
    description:
      "A laser-cut girih star pattern in oiled walnut, mounted on a linen-wrapped board so the geometry casts its own shadow.",
    material: "Walnut, linen board",
    color: "Walnut",
    style: "Traditional",
    rooms: ["living", "office", "entrance"],
    dimensions: "70 x 70 cm",
    inStock: true,
    imageKey: "islamic",
    gallery: ["islamic", "wall-decor"],
    tags: ["islamic", "geometric", "walnut", "panel", "girih"],
    isHandmade: true,
    popularity: 60,
  },
  {
    id: "lh-066",
    name: "Multan Blue Traditional Pottery Vase",
    category: "islamic",
    subcategory: "Traditional Pottery",
    price: 8600,
    rating: 4.7,
    reviews: 58,
    description:
      "Hand-thrown and hand-painted in Multan in the traditional cobalt and turquoise palette, glazed to a soft sheen.",
    material: "Hand-painted earthenware",
    color: "Cobalt Blue",
    style: "Traditional",
    rooms: ["living", "dining", "entrance"],
    dimensions: "Ø 20 x 34 cm",
    inStock: true,
    imageKey: "handmade",
    gallery: ["handmade", "islamic"],
    tags: ["pottery", "multan", "handmade", "cultural", "vase"],
    isHandmade: true,
    popularity: 67,
  },

  // ---------- Handmade ----------
  {
    id: "lh-067",
    name: "Terre Hand-Thrown Stoneware Vase",
    category: "handmade",
    subcategory: "Handmade Pottery",
    price: 10400,
    rating: 4.8,
    reviews: 63,
    description:
      "Thrown on the wheel and finished in a reactive sand glaze, so no two pieces break the same way. Signed on the base.",
    material: "Stoneware",
    color: "Sand",
    style: "Artisan",
    rooms: ["living", "dining", "entrance"],
    dimensions: "Ø 18 x 32 cm",
    inStock: true,
    imageKey: "handmade",
    gallery: ["handmade", "vases"],
    tags: ["handmade", "pottery", "stoneware", "artisan", "vase"],
    isHandmade: true,
    isLuxury: true,
    popularity: 80,
  },
  {
    id: "lh-068",
    name: "Rattan Woven Wall Disc",
    category: "handmade",
    subcategory: "Rattan Decor",
    price: 5200,
    rating: 4.5,
    reviews: 51,
    description:
      "A hand-woven rattan sunburst disc with an open centre — texture on a wall without competing with framed art.",
    material: "Natural rattan",
    color: "Natural",
    style: "Boho",
    rooms: ["living", "bedroom", "balcony"],
    dimensions: "Ø 60 cm",
    inStock: true,
    imageKey: "handmade",
    gallery: ["handmade"],
    tags: ["rattan", "handmade", "wall", "boho", "texture"],
    isHandmade: true,
    popularity: 57,
  },
  {
    id: "lh-069",
    name: "Fil Embroidered Linen Wall Art",
    category: "handmade",
    subcategory: "Embroidered Wall Art",
    price: 8800,
    rating: 4.6,
    reviews: 36,
    description:
      "A hand-embroidered abstract landscape in tonal beige and espresso thread on natural linen, stretched over an oak frame.",
    material: "Linen, cotton thread, oak",
    color: "Beige",
    style: "Artisan",
    rooms: ["living", "bedroom", "office"],
    dimensions: "45 x 60 cm",
    inStock: true,
    imageKey: "handmade",
    gallery: ["handmade", "wall-decor"],
    tags: ["embroidery", "handmade", "wall art", "linen", "artisan"],
    isHandmade: true,
    popularity: 52,
  },
  {
    id: "lh-070",
    name: "Cire Hand-Poured Soy Candle Pair",
    category: "handmade",
    subcategory: "Handmade Candles",
    price: 5400,
    rating: 4.7,
    reviews: 79,
    description:
      "Two hand-poured soy candles in hand-thrown clay cups — bergamot cedar and warm fig — with lids that double as coasters.",
    material: "Soy wax, clay",
    color: "Clay",
    style: "Artisan",
    rooms: ["living", "bedroom", "bathroom"],
    dimensions: "2 x 200 g",
    inStock: true,
    imageKey: "candles",
    gallery: ["candles", "handmade"],
    tags: ["candle", "handmade", "soy", "gift", "set"],
    isHandmade: true,
    popularity: 71,
  },
];

/* ---------------- helpers ---------------- */

export const getProduct = (id: string): Product | undefined =>
  PRODUCTS.find((p) => p.id === id);

export const relatedProducts = (product: Product, limit = 4): Product[] =>
  PRODUCTS.filter((p) => p.id !== product.id)
    .map((p) => {
      let score = 0;
      if (p.category === product.category) score += 5;
      if (p.subcategory === product.subcategory) score += 3;
      score += p.rooms.filter((r) => product.rooms.includes(r)).length;
      score += p.tags.filter((t) => product.tags.includes(t)).length;
      if (p.style === product.style) score += 1;
      return { p, score };
    })
    .sort((a, b) => b.score - a.score || b.p.popularity - a.p.popularity)
    .slice(0, limit)
    .map((x) => x.p);

export const searchProducts = (query: string, limit?: number): Product[] => {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const terms = q.split(/\s+/);
  const results = PRODUCTS.map((p) => {
    const haystack = [
      p.name,
      categoryName(p.category),
      p.subcategory,
      p.material,
      p.style,
      p.color,
      ...p.tags,
      ...p.rooms.map(roomName),
    ]
      .join(" ")
      .toLowerCase();
    const score = terms.reduce(
      (acc, t) => acc + (haystack.includes(t) ? (p.name.toLowerCase().includes(t) ? 3 : 1) : 0),
      0,
    );
    return { p, score };
  })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score || b.p.popularity - a.p.popularity)
    .map((x) => x.p);
  return limit ? results.slice(0, limit) : results;
};

export const newArrivals = (limit = 8) =>
  [...PRODUCTS]
    .sort((a, b) => Number(!!b.isNew) - Number(!!a.isNew) || b.id.localeCompare(a.id))
    .slice(0, limit);

export const bestSellers = (limit = 8) =>
  PRODUCTS.filter((p) => p.isBestSeller)
    .sort((a, b) => b.popularity - a.popularity)
    .slice(0, limit);

export const luxuryCollection = (limit = 6) =>
  PRODUCTS.filter((p) => p.isLuxury)
    .sort((a, b) => finalPrice(b) - finalPrice(a))
    .slice(0, limit);

export const handmadeCollection = (limit = 6) =>
  PRODUCTS.filter((p) => p.isHandmade)
    .sort((a, b) => b.popularity - a.popularity)
    .slice(0, limit);

export const productsByRoom = (roomSlug: string) =>
  PRODUCTS.filter((p) => p.rooms.includes(roomSlug)).sort(
    (a, b) => b.popularity - a.popularity,
  );

export const productsByCategory = (categorySlug: string) =>
  PRODUCTS.filter((p) => p.category === categorySlug);

export const ALL_COLORS = Array.from(new Set(PRODUCTS.map((p) => p.color))).sort();
export const ALL_MATERIALS = Array.from(
  new Set(PRODUCTS.map((p) => p.material.split(",")[0].trim())),
).sort();
export const ALL_STYLES = Array.from(new Set(PRODUCTS.map((p) => p.style))).sort();
export const PRICE_MAX = Math.max(...PRODUCTS.map((p) => finalPrice(p)));

/** Budget decorator: greedily builds the richest collection under a budget. */
export function buildBudgetCollection(budget: number, roomSlug: string): Product[] {
  const pool = productsByRoom(roomSlug)
    .filter((p) => p.inStock)
    .sort((a, b) => b.rating * b.popularity - a.rating * a.popularity);

  const picked: Product[] = [];
  const usedCategories = new Set<string>();
  let total = 0;

  // First pass: one hero piece per category, largest first.
  for (const p of [...pool].sort((a, b) => finalPrice(b) - finalPrice(a))) {
    if (usedCategories.has(p.category)) continue;
    if (total + finalPrice(p) > budget) continue;
    picked.push(p);
    usedCategories.add(p.category);
    total += finalPrice(p);
  }
  // Second pass: fill remaining budget with smaller accents.
  for (const p of [...pool].sort((a, b) => finalPrice(a) - finalPrice(b))) {
    if (picked.some((x) => x.id === p.id)) continue;
    if (total + finalPrice(p) > budget) continue;
    picked.push(p);
    total += finalPrice(p);
    if (picked.length >= 10) break;
  }
  return picked.sort((a, b) => finalPrice(b) - finalPrice(a));
}

/** Shop-the-look hotspots, positioned as percentages over the look image. */
export const SHOP_THE_LOOK: { id: string; productId: string; x: number; y: number }[] = [
  { id: "h1", productId: "lh-037", x: 17, y: 46 },
  { id: "h2", productId: "lh-001", x: 37, y: 26 },
  { id: "h3", productId: "lh-015", x: 58, y: 30 },
  { id: "h4", productId: "lh-031", x: 78, y: 62 },
  { id: "h5", productId: "lh-027", x: 30, y: 90 },
];

export const COUPONS: Record<string, { type: "percent" | "flat"; value: number; label: string }> = {
  LUMIERE10: { type: "percent", value: 10, label: "10% off your order" },
  ELEVATE15: { type: "percent", value: 15, label: "15% off your order" },
  WELCOME500: { type: "flat", value: 500, label: "₨500 off your order" },
};

export const PK_CITIES = [
  "Karachi",
  "Lahore",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Peshawar",
  "Quetta",
  "Hyderabad",
  "Sialkot",
];
