import type { Product } from "./products";

type Draft = Omit<Product, "gallery" | "inStock"> & {
  gallery?: string[];
  inStock?: boolean;
};

const build = (d: Draft): Product => ({
  ...d,
  inStock: d.inStock ?? true,
  gallery: d.gallery ?? [d.imageKey],
});

/**
 * Second wave of the catalogue. Every entry here is tagged to the rooms it
 * genuinely belongs in (max two), so rooms and categories stop repeating the
 * same pieces across the site.
 */
export const EXTRA_PRODUCTS: Product[] = [
  /* ---------------- Kids Room ---------------- */
  build({
    id: "lh-071",
    name: "Meadow Animal Wall Decal Set",
    category: "kids",
    subcategory: "Kids Wall Decor",
    price: 3200,
    rating: 4.6,
    reviews: 74,
    description:
      "Twenty-two peel-and-stick decals — deer, rabbits, birds and grasses — printed in soft clay and sage so a nursery wall stays calm.",
    material: "Matte vinyl",
    color: "Blush",
    style: "Modern",
    rooms: ["kids"],
    dimensions: "Sheet 60 x 90 cm",
    imageKey: "kids-stickers",
    gallery: ["kids-stickers", "kids-posters"],
    tags: ["kids", "decal", "sticker", "nursery", "animals"],
    isNew: true,
    popularity: 64,
  }),
  build({
    id: "lh-072",
    name: "Petit Alphabet Poster Trio",
    category: "kids",
    subcategory: "Kids Wall Art",
    price: 5400,
    discount: 10,
    rating: 4.7,
    reviews: 58,
    description:
      "Three oak-framed prints — alphabet, bird and fawn — drawn in muted pastels that grow with the room rather than shouting at it.",
    material: "Fine-art paper, oak frames",
    color: "Ivory",
    style: "Scandinavian",
    rooms: ["kids"],
    dimensions: "3 x 30 x 40 cm",
    imageKey: "kids-posters",
    gallery: ["kids-posters", "kids-stickers"],
    tags: ["kids", "poster", "frame", "alphabet", "nursery"],
    popularity: 61,
  }),
  build({
    id: "lh-073",
    name: "Nimbus Cloud Night Light",
    category: "kids",
    subcategory: "Kids Lighting",
    price: 4600,
    rating: 4.8,
    reviews: 96,
    description:
      "A soft silicone cloud with three warmth settings and a timer, rechargeable and cool to the touch for small hands.",
    material: "Food-grade silicone",
    color: "Cream",
    style: "Modern",
    rooms: ["kids"],
    dimensions: "18 x 12 x 12 cm",
    imageKey: "kids-lighting",
    tags: ["kids", "night light", "lamp", "rechargeable", "nursery"],
    isBestSeller: true,
    popularity: 88,
  }),
  build({
    id: "lh-074",
    name: "Constellation Star Projector",
    category: "kids",
    subcategory: "Kids Lighting",
    price: 6900,
    rating: 4.5,
    reviews: 63,
    description:
      "Casts a slow-drifting field of stars across the ceiling with a 45-minute sleep timer and a warm amber mode.",
    material: "ABS, optical lens",
    color: "White",
    style: "Modern",
    rooms: ["kids"],
    dimensions: "Ø 12 x 15 cm",
    imageKey: "kids-lighting",
    gallery: ["kids-lighting", "kids-posters"],
    tags: ["kids", "projector", "stars", "night light", "sleep"],
    popularity: 72,
  }),
  build({
    id: "lh-075",
    name: "Rope Coil Toy Basket",
    category: "kids",
    subcategory: "Kids Storage",
    price: 3900,
    rating: 4.6,
    reviews: 81,
    description:
      "Coiled cotton rope with soft handles — deep enough for blocks and soft toys, light enough for a child to drag.",
    material: "Cotton rope",
    color: "Natural",
    style: "Boho",
    rooms: ["kids"],
    dimensions: "Ø 38 x 36 cm",
    imageKey: "kids-storage",
    tags: ["kids", "basket", "storage", "toys", "rope"],
    isHandmade: true,
    popularity: 70,
  }),
  build({
    id: "lh-076",
    name: "Nest Nursery Basket Set of Three",
    category: "kids",
    subcategory: "Kids Storage",
    price: 6200,
    discount: 12,
    rating: 4.5,
    reviews: 47,
    description:
      "Three nesting baskets in graduated sizes for nappies, books and small chaos — woven by hand with reinforced rims.",
    material: "Cotton rope, jute",
    color: "Beige",
    style: "Boho",
    rooms: ["kids"],
    dimensions: "Ø 24 / 30 / 38 cm",
    imageKey: "kids-storage",
    gallery: ["kids-storage", "storage"],
    tags: ["kids", "basket", "nesting", "storage", "nursery"],
    isHandmade: true,
    popularity: 58,
  }),
  build({
    id: "lh-077",
    name: "Little Explorer Name Plaque",
    category: "kids",
    subcategory: "Kids Personalized",
    price: 4200,
    rating: 4.7,
    reviews: 39,
    description:
      "A birch plaque engraved with your child's name in a rounded script, finished with a natural oil and ready to hang.",
    material: "Birch ply",
    color: "Natural",
    style: "Scandinavian",
    rooms: ["kids"],
    dimensions: "40 x 14 cm",
    imageKey: "kids-posters",
    gallery: ["kids-posters", "entry-signs"],
    tags: ["kids", "personalized", "name", "wooden", "nursery"],
    isHandmade: true,
    popularity: 55,
  }),
  build({
    id: "lh-078",
    name: "Pastel Growth Chart Ruler",
    category: "kids",
    subcategory: "Kids Wall Decor",
    price: 3800,
    rating: 4.4,
    reviews: 44,
    description:
      "A tall oak ruler marked to 150 cm, ready for a decade of pencil lines and dates.",
    material: "Solid oak",
    color: "Oak",
    style: "Scandinavian",
    rooms: ["kids"],
    dimensions: "150 x 20 cm",
    imageKey: "kids-stickers",
    gallery: ["kids-stickers", "kids-posters"],
    tags: ["kids", "growth chart", "wooden", "nursery", "wall"],
    isNew: true,
    popularity: 49,
  }),
  build({
    id: "lh-079",
    name: "Cloud Nine Kids Play Rug",
    category: "kids",
    subcategory: "Kids Rugs",
    price: 12800,
    discount: 15,
    rating: 4.6,
    reviews: 52,
    description:
      "A thick tufted cotton rug in cloud form, soft enough for floor play and machine-washable at 30°C.",
    material: "Tufted cotton",
    color: "Ivory",
    style: "Modern",
    rooms: ["kids"],
    dimensions: "120 x 160 cm",
    imageKey: "kids-storage",
    gallery: ["kids-storage", "rugs"],
    tags: ["kids", "rug", "play", "cotton", "washable"],
    popularity: 66,
  }),
  build({
    id: "lh-080",
    name: "Story Time Wall Book Ledge",
    category: "kids",
    subcategory: "Kids Storage",
    price: 5600,
    rating: 4.7,
    reviews: 35,
    description:
      "A pair of shallow pine ledges that display picture books cover-out, so children pick with their eyes.",
    material: "Pine",
    color: "Natural",
    style: "Scandinavian",
    rooms: ["kids"],
    dimensions: "2 x 60 x 10 cm",
    imageKey: "kids-posters",
    gallery: ["kids-posters", "storage"],
    tags: ["kids", "shelf", "books", "ledge", "nursery"],
    popularity: 51,
  }),

  /* ---------------- Bathroom ---------------- */
  build({
    id: "lh-081",
    name: "Stone Ridge Soap Dispenser",
    category: "storage",
    subcategory: "Bathroom Organisers",
    price: 3400,
    rating: 4.6,
    reviews: 88,
    description:
      "A weighted ceramic dispenser in matte oat with a brushed brass pump that will not corrode in a humid bathroom.",
    material: "Ceramic, brass",
    color: "Oat",
    style: "Minimal",
    rooms: ["bathroom"],
    dimensions: "Ø 8 x 18 cm",
    imageKey: "bath-accessories",
    tags: ["bathroom", "dispenser", "ceramic", "brass", "vanity"],
    isBestSeller: true,
    popularity: 83,
  }),
  build({
    id: "lh-082",
    name: "Marbre Vanity Tray",
    category: "tabletop",
    subcategory: "Decorative Trays",
    price: 5200,
    rating: 4.7,
    reviews: 41,
    description:
      "Honed marble with a low brass gallery rail — corrals scent, soap and jewellery into one composed square.",
    material: "Marble, brass",
    color: "White",
    style: "Luxury",
    rooms: ["bathroom"],
    dimensions: "26 x 18 cm",
    imageKey: "bath-accessories",
    gallery: ["bath-accessories", "tabletop"],
    tags: ["bathroom", "tray", "marble", "brass", "vanity"],
    isLuxury: true,
    popularity: 68,
  }),
  build({
    id: "lh-083",
    name: "Teak Slatted Bath Mat",
    category: "storage",
    subcategory: "Bathroom Organisers",
    price: 8900,
    discount: 10,
    rating: 4.8,
    reviews: 57,
    description:
      "Oiled teak slats raised on rubber feet so water drains straight through — the spa detail that costs least to add.",
    material: "Solid teak",
    color: "Teak",
    style: "Spa",
    rooms: ["bathroom"],
    dimensions: "60 x 40 cm",
    imageKey: "bath-storage",
    tags: ["bathroom", "teak", "mat", "spa", "wood"],
    popularity: 74,
  }),
  build({
    id: "lh-084",
    name: "Onda Woven Towel Basket",
    category: "storage",
    subcategory: "Woven Baskets",
    price: 4800,
    rating: 4.5,
    reviews: 62,
    description:
      "A tall seagrass basket sized to hold four rolled bath sheets beside the tub.",
    material: "Seagrass",
    color: "Natural",
    style: "Coastal",
    rooms: ["bathroom"],
    dimensions: "Ø 36 x 45 cm",
    imageKey: "bath-storage",
    gallery: ["bath-storage", "storage"],
    tags: ["bathroom", "basket", "towels", "seagrass", "storage"],
    isHandmade: true,
    popularity: 60,
  }),
  build({
    id: "lh-085",
    name: "Lume Ribbed Glass Jar Duo",
    category: "storage",
    subcategory: "Bathroom Organisers",
    price: 3600,
    rating: 4.4,
    reviews: 36,
    description:
      "Two ribbed glass apothecary jars with oak lids for cotton, salts or bath cubes.",
    material: "Glass, oak",
    color: "Clear",
    style: "Minimal",
    rooms: ["bathroom"],
    dimensions: "2 x Ø 10 x 14 cm",
    imageKey: "bath-accessories",
    gallery: ["bath-accessories", "kitchen-jars"],
    tags: ["bathroom", "jar", "glass", "storage", "apothecary"],
    isNew: true,
    popularity: 53,
  }),
  build({
    id: "lh-086",
    name: "Hammam Fringed Towel Set",
    category: "soft-decor",
    subcategory: "Bath Textiles",
    price: 7400,
    rating: 4.7,
    reviews: 49,
    description:
      "Two Turkish-woven cotton peshtemals in sand stripe — quick-drying, light to fold and softer with every wash.",
    material: "Turkish cotton",
    color: "Sand",
    style: "Coastal",
    rooms: ["bathroom"],
    dimensions: "2 x 90 x 170 cm",
    imageKey: "bath-storage",
    gallery: ["bath-storage", "soft-decor"],
    tags: ["bathroom", "towel", "cotton", "hammam", "textile"],
    popularity: 62,
  }),
  build({
    id: "lh-087",
    name: "Eucalyptus Shower Bundle",
    category: "plants",
    subcategory: "Dried Botanicals",
    price: 2400,
    rating: 4.6,
    reviews: 70,
    description:
      "A tied bunch of preserved eucalyptus for the shower rail — steam releases the scent for weeks.",
    material: "Preserved eucalyptus",
    color: "Sage",
    style: "Natural",
    rooms: ["bathroom"],
    dimensions: "45 cm bunch",
    imageKey: "bath-accessories",
    gallery: ["bath-accessories", "plants"],
    tags: ["bathroom", "eucalyptus", "dried", "botanical", "spa"],
    isNew: true,
    popularity: 57,
  }),
  build({
    id: "lh-088",
    name: "Cedar & Sea Salt Reed Diffuser",
    category: "candles",
    subcategory: "Reed Diffusers",
    price: 5800,
    rating: 4.7,
    reviews: 84,
    description:
      "An amber glass diffuser with natural rattan reeds — cedar, sea salt and a dry vetiver base that lasts twelve weeks.",
    material: "Glass, rattan reeds",
    color: "Amber",
    style: "Luxury",
    rooms: ["bathroom", "entrance"],
    dimensions: "200 ml",
    imageKey: "diffusers",
    tags: ["diffuser", "fragrance", "reed", "cedar", "bathroom"],
    isBestSeller: true,
    popularity: 86,
  }),

  /* ---------------- Kitchen & Dining ---------------- */
  build({
    id: "lh-089",
    name: "Sablé Ceramic Canister Set",
    category: "storage",
    subcategory: "Kitchen Storage",
    price: 9400,
    discount: 12,
    rating: 4.8,
    reviews: 93,
    description:
      "Three matte stoneware canisters with airtight beech lids and silicone seals — flour, sugar, coffee, kept quiet.",
    material: "Stoneware, beech",
    color: "Oat",
    style: "Minimal",
    rooms: ["dining"],
    dimensions: "3 x Ø 12 x 18 cm",
    imageKey: "kitchen-jars",
    tags: ["kitchen", "canister", "ceramic", "storage", "airtight"],
    isBestSeller: true,
    popularity: 87,
  }),
  build({
    id: "lh-090",
    name: "Clair Glass Pantry Jars",
    category: "storage",
    subcategory: "Kitchen Storage",
    price: 6800,
    rating: 4.6,
    reviews: 66,
    description:
      "Four tall borosilicate jars with bamboo lids, sized to line up neatly on an open shelf.",
    material: "Borosilicate glass, bamboo",
    color: "Clear",
    style: "Minimal",
    rooms: ["dining"],
    dimensions: "4 x Ø 10 x 22 cm",
    imageKey: "kitchen-jars",
    gallery: ["kitchen-jars", "storage"],
    tags: ["kitchen", "jar", "glass", "pantry", "storage"],
    popularity: 71,
  }),
  build({
    id: "lh-091",
    name: "Lin Naturel Table Runner",
    category: "tabletop",
    subcategory: "Table Linen",
    price: 4600,
    rating: 4.7,
    reviews: 58,
    description:
      "Stonewashed pure linen with hand-knotted fringing — creases on purpose, softens with every wash.",
    material: "Washed linen",
    color: "Sand",
    style: "Rustic",
    rooms: ["dining"],
    dimensions: "40 x 200 cm",
    imageKey: "dining-table",
    tags: ["dining", "runner", "linen", "table", "textile"],
    popularity: 69,
  }),
  build({
    id: "lh-092",
    name: "Terre Serving Bowl Pair",
    category: "tabletop",
    subcategory: "Serveware",
    price: 7200,
    rating: 4.8,
    reviews: 51,
    description:
      "Two wide stoneware bowls with a reactive cream glaze, deep enough for salad and handsome enough to leave out.",
    material: "Stoneware",
    color: "Cream",
    style: "Artisan",
    rooms: ["dining"],
    dimensions: "2 x Ø 26 x 9 cm",
    imageKey: "dining-table",
    gallery: ["dining-table", "tabletop"],
    tags: ["dining", "bowl", "serveware", "stoneware", "table"],
    isHandmade: true,
    popularity: 73,
  }),
  build({
    id: "lh-093",
    name: "Aube Stoneware Dinner Set",
    category: "tabletop",
    subcategory: "Dinnerware",
    price: 21500,
    discount: 15,
    rating: 4.8,
    reviews: 77,
    description:
      "A sixteen-piece service in speckled oat glaze — dinner, side, bowl and mug for four, all dishwasher safe.",
    material: "Speckled stoneware",
    color: "Oat",
    style: "Modern",
    rooms: ["dining"],
    dimensions: "16 pieces",
    imageKey: "dining-table",
    gallery: ["dining-table", "kitchen-jars"],
    tags: ["dining", "dinnerware", "plates", "stoneware", "set"],
    isLuxury: true,
    popularity: 81,
  }),
  build({
    id: "lh-094",
    name: "Olive Wood Board & Bowl",
    category: "tabletop",
    subcategory: "Serveware",
    price: 6400,
    rating: 4.6,
    reviews: 44,
    description:
      "A long olive-wood serving board with a matching dip bowl, each grained differently by the tree it came from.",
    material: "Olive wood",
    color: "Walnut",
    style: "Rustic",
    rooms: ["dining"],
    dimensions: "50 x 18 cm",
    imageKey: "kitchen-jars",
    gallery: ["kitchen-jars", "dining-table"],
    tags: ["dining", "board", "wood", "serveware", "cheese"],
    isHandmade: true,
    popularity: 64,
  }),
  build({
    id: "lh-095",
    name: "Brass Taper Candle Holders",
    category: "candles",
    subcategory: "Candle Holders",
    price: 5900,
    rating: 4.7,
    reviews: 68,
    description:
      "A trio of turned brass holders at three heights — the easiest way to make a weeknight table feel considered.",
    material: "Solid brass",
    color: "Brass",
    style: "Classic",
    rooms: ["dining"],
    dimensions: "18 / 24 / 30 cm",
    imageKey: "candle-holders",
    tags: ["dining", "candle holder", "brass", "taper", "table"],
    isBestSeller: true,
    popularity: 84,
  }),
  build({
    id: "lh-096",
    name: "Ivoire Taper Candle Box",
    category: "candles",
    subcategory: "Taper Candles",
    price: 2800,
    rating: 4.5,
    reviews: 55,
    description:
      "Twelve unscented ivory tapers in dripless beeswax blend, sized for standard holders.",
    material: "Beeswax blend",
    color: "Ivory",
    style: "Classic",
    rooms: ["dining"],
    dimensions: "12 x 25 cm",
    imageKey: "candle-holders",
    gallery: ["candle-holders", "candles"],
    tags: ["dining", "candle", "taper", "beeswax", "table"],
    popularity: 59,
  }),
  build({
    id: "lh-097",
    name: "Grès Woven Placemat Set",
    category: "tabletop",
    subcategory: "Placemats",
    price: 3900,
    rating: 4.5,
    reviews: 47,
    description:
      "Six hand-woven water-hyacinth mats that wipe clean and warm up a stone or glass table instantly.",
    material: "Water hyacinth",
    color: "Natural",
    style: "Rustic",
    rooms: ["dining"],
    dimensions: "6 x Ø 38 cm",
    imageKey: "dining-table",
    gallery: ["dining-table", "handmade"],
    tags: ["dining", "placemat", "woven", "natural", "table"],
    isHandmade: true,
    popularity: 56,
  }),

  /* ---------------- Home Office ---------------- */
  build({
    id: "lh-098",
    name: "Noyer Walnut Desk Organiser",
    category: "storage",
    subcategory: "Desk Organisers",
    price: 7600,
    rating: 4.7,
    reviews: 61,
    description:
      "A solid walnut tray with divided wells for pens, cards and the small objects that otherwise migrate.",
    material: "Solid walnut",
    color: "Walnut",
    style: "Minimal",
    rooms: ["office"],
    dimensions: "36 x 14 x 7 cm",
    imageKey: "office-desk",
    tags: ["office", "desk", "organiser", "walnut", "storage"],
    isBestSeller: true,
    popularity: 79,
  }),
  build({
    id: "lh-099",
    name: "Marbre Bookend Pair",
    category: "showpieces",
    subcategory: "Bookends",
    price: 6200,
    rating: 4.6,
    reviews: 38,
    description:
      "Two solid marble blocks with felted bases — heavy enough for a full shelf, plain enough to disappear.",
    material: "Marble",
    color: "White",
    style: "Minimal",
    rooms: ["office"],
    dimensions: "2 x 8 x 15 cm",
    imageKey: "office-desk",
    gallery: ["office-desk", "showpieces"],
    tags: ["office", "bookend", "marble", "shelf", "study"],
    isLuxury: true,
    popularity: 63,
  }),
  build({
    id: "lh-100",
    name: "Halo Brass Task Lamp",
    category: "lighting",
    subcategory: "Desk Lamps",
    price: 14500,
    discount: 10,
    rating: 4.8,
    reviews: 72,
    description:
      "A pivoting dome shade in brushed brass on a weighted base, dimmable through three warm levels.",
    material: "Brushed brass, steel",
    color: "Brass",
    style: "Modern",
    rooms: ["office"],
    dimensions: "42 x 18 cm",
    imageKey: "office-desk",
    gallery: ["office-desk", "lighting"],
    tags: ["office", "lamp", "desk", "brass", "task light"],
    isLuxury: true,
    popularity: 82,
  }),
  build({
    id: "lh-101",
    name: "Sillon Cork Pin Board",
    category: "wall-decor",
    subcategory: "Wall Boards",
    price: 5400,
    rating: 4.4,
    reviews: 33,
    description:
      "Natural cork in a thin oak frame — a soft wall for notes, prints and the plan of the week.",
    material: "Cork, oak",
    color: "Natural",
    style: "Scandinavian",
    rooms: ["office"],
    dimensions: "60 x 45 cm",
    imageKey: "office-desk",
    gallery: ["office-desk", "wall-decor"],
    tags: ["office", "pinboard", "cork", "wall", "study"],
    isNew: true,
    popularity: 48,
  }),
  build({
    id: "lh-102",
    name: "Petit Desk Succulent Trio",
    category: "plants",
    subcategory: "Mini Plants",
    price: 3400,
    rating: 4.5,
    reviews: 57,
    description:
      "Three lifelike faux succulents in small brass-rimmed concrete pots, sized for a desk edge or shelf.",
    material: "Polyester, concrete, brass",
    color: "Green",
    style: "Modern",
    rooms: ["office"],
    dimensions: "3 x Ø 8 x 12 cm",
    imageKey: "office-desk",
    gallery: ["office-desk", "plants"],
    tags: ["office", "succulent", "faux plant", "desk", "green"],
    popularity: 66,
  }),
  build({
    id: "lh-103",
    name: "Ordre Linen File Boxes",
    category: "storage",
    subcategory: "Document Storage",
    price: 6900,
    rating: 4.5,
    reviews: 29,
    description:
      "A pair of linen-wrapped archive boxes with brass label frames — paperwork that looks like it belongs on a shelf.",
    material: "Linen board, brass",
    color: "Sand",
    style: "Minimal",
    rooms: ["office"],
    dimensions: "2 x 34 x 26 x 10 cm",
    imageKey: "office-desk",
    gallery: ["office-desk", "storage"],
    tags: ["office", "box", "files", "linen", "storage"],
    popularity: 45,
  }),
  build({
    id: "lh-104",
    name: "Meridian Minimal Wall Clock",
    category: "wall-decor",
    subcategory: "Wall Clocks",
    price: 8200,
    rating: 4.7,
    reviews: 64,
    description:
      "An oak-rimmed clock with slim brass batons and a silent sweep movement — quiet enough for a study wall.",
    material: "Oak, brass, glass",
    color: "Oak",
    style: "Modern",
    rooms: ["office", "living"],
    dimensions: "Ø 45 cm",
    imageKey: "wall-clocks",
    tags: ["clock", "wall", "oak", "brass", "silent"],
    isBestSeller: true,
    popularity: 85,
  }),
  build({
    id: "lh-105",
    name: "Grand Roman Numeral Clock",
    category: "wall-decor",
    subcategory: "Wall Clocks",
    price: 12400,
    discount: 12,
    rating: 4.6,
    reviews: 41,
    description:
      "An oversized statement clock with walnut numerals on a bone dial, made to anchor a long console wall.",
    material: "Walnut, steel",
    color: "Walnut",
    style: "Classic",
    rooms: ["living", "entrance"],
    dimensions: "Ø 70 cm",
    imageKey: "wall-clocks",
    gallery: ["wall-clocks", "wall-decor"],
    tags: ["clock", "wall", "statement", "walnut", "living"],
    isLuxury: true,
    popularity: 70,
  }),

  /* ---------------- Entrance ---------------- */
  build({
    id: "lh-106",
    name: "Maison Engraved Name Plate",
    category: "personalized",
    subcategory: "Name Plates",
    price: 5600,
    rating: 4.7,
    reviews: 52,
    description:
      "Solid sheesham engraved with your family name in a serif of your choosing, oiled and fitted with hidden mounts.",
    material: "Sheesham wood",
    color: "Walnut",
    style: "Classic",
    rooms: ["entrance"],
    dimensions: "45 x 14 cm",
    imageKey: "entry-signs",
    tags: ["entrance", "nameplate", "personalized", "wood", "engraved"],
    isHandmade: true,
    isBestSeller: true,
    popularity: 80,
  }),
  build({
    id: "lh-107",
    name: "Clé Brass Key Rail",
    category: "entryway",
    subcategory: "Key Holders",
    price: 3600,
    rating: 4.5,
    reviews: 46,
    description:
      "Three cast brass hooks on an oiled walnut rail — keys, leads and the small bag that never has a home.",
    material: "Brass, walnut",
    color: "Brass",
    style: "Classic",
    rooms: ["entrance"],
    dimensions: "30 x 6 cm",
    imageKey: "entry-signs",
    gallery: ["entry-signs", "entryway"],
    tags: ["entrance", "key holder", "brass", "hooks", "hallway"],
    popularity: 61,
  }),
  build({
    id: "lh-108",
    name: "Filigree Brass Entry Tray",
    category: "entryway",
    subcategory: "Console Trays",
    price: 4900,
    rating: 4.6,
    reviews: 37,
    description:
      "A pierced brass tray with a raised gallery, aged by hand so it reads antique rather than shiny.",
    material: "Antiqued brass",
    color: "Brass",
    style: "Traditional",
    rooms: ["entrance"],
    dimensions: "Ø 34 cm",
    imageKey: "entry-signs",
    gallery: ["entry-signs", "tabletop"],
    tags: ["entrance", "tray", "brass", "console", "hallway"],
    isHandmade: true,
    popularity: 58,
  }),
  build({
    id: "lh-109",
    name: "Arc Brass Vanity Mirror",
    category: "mirrors",
    subcategory: "Arch Mirrors",
    price: 26500,
    discount: 15,
    rating: 4.9,
    reviews: 88,
    description:
      "A tall arched mirror in a slim brass frame — over a dresser it doubles the light in a bedroom without adding bulk.",
    material: "Brass, glass",
    color: "Brass",
    style: "Luxury",
    rooms: ["bedroom"],
    dimensions: "70 x 110 cm",
    imageKey: "vanity-mirror",
    tags: ["mirror", "arch", "brass", "vanity", "bedroom"],
    isLuxury: true,
    isBestSeller: true,
    popularity: 92,
  }),
  build({
    id: "lh-110",
    name: "Dresser Jewellery Tray & Dish",
    category: "storage",
    subcategory: "Dresser Storage",
    price: 4400,
    rating: 4.6,
    reviews: 43,
    description:
      "A brass-edged tray with a small ring dish, made to sit under a mirror and catch the day's jewellery.",
    material: "Brass, wood",
    color: "Brass",
    style: "Luxury",
    rooms: ["bedroom"],
    dimensions: "30 x 20 cm",
    imageKey: "vanity-mirror",
    gallery: ["vanity-mirror", "tabletop"],
    tags: ["bedroom", "tray", "jewellery", "brass", "dresser"],
    popularity: 60,
  }),
  build({
    id: "lh-111",
    name: "Rose Neroli Room Diffuser",
    category: "candles",
    subcategory: "Reed Diffusers",
    price: 6200,
    rating: 4.7,
    reviews: 54,
    description:
      "Rose, neroli and soft amber in smoked glass — placed on a dresser it scents a bedroom for three months.",
    material: "Smoked glass, reeds",
    color: "Amber",
    style: "Luxury",
    rooms: ["bedroom"],
    dimensions: "250 ml",
    imageKey: "diffusers",
    gallery: ["diffusers", "vanity-mirror"],
    tags: ["diffuser", "fragrance", "rose", "bedroom", "reed"],
    isLuxury: true,
    popularity: 74,
  }),
  build({
    id: "lh-112",
    name: "Brume Ultrasonic Aroma Diffuser",
    category: "candles",
    subcategory: "Aroma Diffusers",
    price: 9800,
    discount: 10,
    rating: 4.6,
    reviews: 79,
    description:
      "A ceramic and walnut ultrasonic diffuser with two mist modes and an auto shut-off, quiet enough for sleep.",
    material: "Ceramic, walnut",
    color: "Cream",
    style: "Modern",
    rooms: ["living", "bedroom"],
    dimensions: "Ø 15 x 13 cm",
    imageKey: "diffusers",
    tags: ["diffuser", "aroma", "ultrasonic", "essential oil", "quiet"],
    isBestSeller: true,
    popularity: 83,
  }),
  build({
    id: "lh-113",
    name: "Nuit Essential Oil Trio",
    category: "candles",
    subcategory: "Essential Oils",
    price: 4200,
    rating: 4.5,
    reviews: 48,
    description:
      "Lavender, cedarwood and sweet orange in amber dropper bottles — a small evening ritual in three parts.",
    material: "Essential oils, glass",
    color: "Amber",
    style: "Minimal",
    rooms: ["bedroom"],
    dimensions: "3 x 15 ml",
    imageKey: "diffusers",
    gallery: ["diffusers", "candles"],
    tags: ["essential oil", "lavender", "aroma", "bedroom", "ritual"],
    isNew: true,
    popularity: 55,
  }),

  /* ---------------- Balcony & Outdoor ---------------- */
  build({
    id: "lh-114",
    name: "Terracotta Ribbed Planter Set",
    category: "plants",
    subcategory: "Planters",
    price: 7800,
    rating: 4.7,
    reviews: 66,
    description:
      "Three ribbed terracotta planters with drainage and matching saucers, frost-tolerant and better with age.",
    material: "Terracotta",
    color: "Terracotta",
    style: "Rustic",
    rooms: ["balcony"],
    dimensions: "Ø 18 / 24 / 30 cm",
    imageKey: "outdoor-planters",
    tags: ["balcony", "planter", "terracotta", "outdoor", "pots"],
    isBestSeller: true,
    popularity: 78,
  }),
  build({
    id: "lh-115",
    name: "Grès Stoneware Floor Planter",
    category: "plants",
    subcategory: "Planters",
    price: 11200,
    discount: 12,
    rating: 4.6,
    reviews: 39,
    description:
      "A tall glazed stoneware planter for a fiddle-leaf or olive tree, weighted at the base against balcony wind.",
    material: "Glazed stoneware",
    color: "Sand",
    style: "Modern",
    rooms: ["balcony"],
    dimensions: "Ø 34 x 45 cm",
    imageKey: "outdoor-planters",
    gallery: ["outdoor-planters", "plants"],
    tags: ["balcony", "planter", "stoneware", "large", "outdoor"],
    popularity: 62,
  }),
  build({
    id: "lh-116",
    name: "Solstice Solar Lantern Pair",
    category: "outdoor",
    subcategory: "Solar Lighting",
    price: 8600,
    rating: 4.7,
    reviews: 71,
    description:
      "Two weatherproof metal-and-glass lanterns that charge by day and glow amber for eight hours after dusk.",
    material: "Powder-coated steel, glass",
    color: "Espresso",
    style: "Modern",
    rooms: ["balcony"],
    dimensions: "2 x 18 x 28 cm",
    imageKey: "outdoor-lighting",
    tags: ["balcony", "lantern", "solar", "outdoor", "lighting"],
    isBestSeller: true,
    popularity: 81,
  }),
  build({
    id: "lh-117",
    name: "Fête Outdoor String Lights",
    category: "outdoor",
    subcategory: "String Lights",
    price: 5400,
    rating: 4.8,
    reviews: 118,
    description:
      "Ten metres of shatterproof warm-white bulbs on a black weatherproof cable — the fastest balcony transformation there is.",
    material: "PVC cable, PC bulbs",
    color: "Warm White",
    style: "Modern",
    rooms: ["balcony"],
    dimensions: "10 m, 20 bulbs",
    imageKey: "outdoor-lighting",
    gallery: ["outdoor-lighting", "lighting"],
    tags: ["balcony", "string lights", "outdoor", "festoon", "warm"],
    isBestSeller: true,
    popularity: 90,
  }),
  build({
    id: "lh-118",
    name: "Corda Outdoor Cushion Pair",
    category: "soft-decor",
    subcategory: "Outdoor Cushions",
    price: 6400,
    rating: 4.5,
    reviews: 42,
    description:
      "Two water-resistant woven cushions in sand and espresso, made to live on a rattan chair through the season.",
    material: "Water-resistant polyester",
    color: "Sand",
    style: "Coastal",
    rooms: ["balcony"],
    dimensions: "2 x 45 x 45 cm",
    imageKey: "outdoor-lighting",
    gallery: ["outdoor-lighting", "soft-decor"],
    tags: ["balcony", "cushion", "outdoor", "weatherproof", "seating"],
    popularity: 57,
  }),
  build({
    id: "lh-119",
    name: "Jardin Hanging Rope Planter",
    category: "plants",
    subcategory: "Hanging Plants",
    price: 3800,
    rating: 4.5,
    reviews: 51,
    description:
      "A macramé hanger with a glazed ceramic pot, ready for trailing pothos on a balcony rail or hook.",
    material: "Cotton rope, ceramic",
    color: "Natural",
    style: "Boho",
    rooms: ["balcony"],
    dimensions: "90 cm drop",
    imageKey: "outdoor-planters",
    gallery: ["outdoor-planters", "handmade"],
    tags: ["balcony", "hanging", "planter", "macrame", "pothos"],
    isHandmade: true,
    popularity: 59,
  }),
  build({
    id: "lh-120",
    name: "Ras Handwoven Balcony Rug",
    category: "rugs",
    subcategory: "Outdoor Rugs",
    price: 13800,
    discount: 15,
    rating: 4.6,
    reviews: 34,
    description:
      "A flatweave PET rug in a sand and charcoal grid — hoses clean, dries fast and softens a concrete floor.",
    material: "Recycled PET",
    color: "Sand",
    style: "Coastal",
    rooms: ["balcony"],
    dimensions: "120 x 180 cm",
    imageKey: "outdoor-planters",
    gallery: ["outdoor-planters", "rugs"],
    tags: ["balcony", "rug", "outdoor", "flatweave", "washable"],
    popularity: 54,
  }),

  /* ---------------- Living & Bedroom refresh ---------------- */
  build({
    id: "lh-121",
    name: "Sables Textured Wall Frieze",
    category: "wall-decor",
    subcategory: "3D Wall Panels",
    price: 15600,
    rating: 4.6,
    reviews: 31,
    description:
      "A carved plaster panel with a slow dune ripple, finished in warm chalk white to catch late afternoon light.",
    material: "Cast plaster",
    color: "Chalk",
    style: "Sculptural",
    rooms: ["living"],
    dimensions: "100 x 50 cm",
    imageKey: "wall-decor",
    gallery: ["wall-decor", "showpieces"],
    tags: ["wall", "panel", "plaster", "sculptural", "living"],
    isNew: true,
    isLuxury: true,
    popularity: 65,
  }),
  build({
    id: "lh-122",
    name: "Ombre Alabaster Table Lamp",
    category: "lighting",
    subcategory: "Table Lamps",
    price: 24500,
    discount: 10,
    rating: 4.8,
    reviews: 57,
    description:
      "A turned alabaster base under a natural linen shade — the stone veining glows when the lamp is lit.",
    material: "Alabaster, linen",
    color: "Ivory",
    style: "Luxury",
    rooms: ["living"],
    dimensions: "38 x 55 cm",
    imageKey: "lighting",
    gallery: ["lighting", "showpieces"],
    tags: ["lamp", "alabaster", "living", "table lamp", "luxury"],
    isLuxury: true,
    popularity: 77,
  }),
  build({
    id: "lh-123",
    name: "Brume Boucle Lumbar Cushion",
    category: "soft-decor",
    subcategory: "Cushion Covers",
    price: 4800,
    rating: 4.6,
    reviews: 63,
    description:
      "A long boucle cushion in warm ivory with a hidden zip and feather-blend insert included.",
    material: "Boucle, feather insert",
    color: "Ivory",
    style: "Modern",
    rooms: ["living"],
    dimensions: "35 x 60 cm",
    imageKey: "soft-decor",
    tags: ["cushion", "boucle", "living", "lumbar", "sofa"],
    popularity: 68,
  }),
  build({
    id: "lh-124",
    name: "Hiver Wool Bed Throw",
    category: "soft-decor",
    subcategory: "Throws",
    price: 12400,
    rating: 4.8,
    reviews: 49,
    description:
      "A brushed lambswool throw with hand-tied fringe, wide enough to fall across the end of a king bed.",
    material: "Lambswool",
    color: "Oat",
    style: "Classic",
    rooms: ["bedroom"],
    dimensions: "140 x 220 cm",
    imageKey: "soft-decor",
    gallery: ["soft-decor", "room-bedroom"],
    tags: ["throw", "wool", "bedroom", "blanket", "bed"],
    isLuxury: true,
    popularity: 72,
  }),
  build({
    id: "lh-125",
    name: "Voile Linen Blackout Curtains",
    category: "curtains",
    subcategory: "Blackout Curtains",
    price: 18900,
    discount: 12,
    rating: 4.7,
    reviews: 58,
    description:
      "A pair of linen-look blackout panels in warm sand with pinch pleats and a triple-weave lining.",
    material: "Linen-look polyester",
    color: "Sand",
    style: "Classic",
    rooms: ["bedroom"],
    dimensions: "2 x 140 x 260 cm",
    imageKey: "curtains",
    tags: ["curtains", "blackout", "bedroom", "linen", "pleated"],
    popularity: 69,
  }),
  build({
    id: "lh-126",
    name: "Aurore Bedside Ceramic Lamp",
    category: "lighting",
    subcategory: "Bedside Lamps",
    price: 11800,
    rating: 4.6,
    reviews: 44,
    description:
      "A rounded ceramic base in matte clay with a cotton drum shade and an inline dimmer within arm's reach.",
    material: "Ceramic, cotton",
    color: "Clay",
    style: "Modern",
    rooms: ["bedroom"],
    dimensions: "28 x 42 cm",
    imageKey: "lighting",
    gallery: ["lighting", "room-bedroom"],
    tags: ["lamp", "bedside", "ceramic", "bedroom", "dimmer"],
    popularity: 67,
  }),
  build({
    id: "lh-127",
    name: "Onde Sculptural Ceramic Vase",
    category: "vases",
    subcategory: "Sculptural Vases",
    price: 9600,
    rating: 4.7,
    reviews: 40,
    description:
      "An asymmetric matte vase with a folded lip, striking enough to stand empty on a console.",
    material: "Matte ceramic",
    color: "Chalk",
    style: "Sculptural",
    rooms: ["living"],
    dimensions: "Ø 20 x 36 cm",
    imageKey: "vases",
    tags: ["vase", "ceramic", "sculptural", "living", "matte"],
    isNew: true,
    popularity: 71,
  }),
  build({
    id: "lh-128",
    name: "Silhouette Marble Sculpture",
    category: "showpieces",
    subcategory: "Abstract Sculptures",
    price: 16800,
    rating: 4.7,
    reviews: 27,
    description:
      "A hand-carved marble ribbon on a walnut plinth — one object doing all the work on an open shelf.",
    material: "Marble, walnut",
    color: "White",
    style: "Sculptural",
    rooms: ["living"],
    dimensions: "18 x 30 cm",
    imageKey: "showpieces",
    tags: ["sculpture", "marble", "living", "shelf", "abstract"],
    isHandmade: true,
    isLuxury: true,
    popularity: 64,
  }),
  build({
    id: "lh-129",
    name: "Bosque Faux Olive Tree",
    category: "plants",
    subcategory: "Artificial Plants",
    price: 22400,
    discount: 15,
    rating: 4.7,
    reviews: 86,
    description:
      "A 150 cm faux olive with real wood trunks and UV-stable leaves, potted in a plain cement planter.",
    material: "Polyester, real wood, cement",
    color: "Green",
    style: "Mediterranean",
    rooms: ["living"],
    dimensions: "150 cm tall",
    imageKey: "plants",
    tags: ["plant", "olive tree", "faux", "living", "tall"],
    isBestSeller: true,
    popularity: 89,
  }),
  build({
    id: "lh-130",
    name: "Cendre Ribbed Storage Ottoman",
    category: "storage",
    subcategory: "Living Storage",
    price: 15400,
    rating: 4.5,
    reviews: 32,
    description:
      "A boucle-topped ottoman with a lift-off lid — throws in, feet up, clutter gone in one move.",
    material: "Boucle, engineered wood",
    color: "Oat",
    style: "Modern",
    rooms: ["living"],
    dimensions: "60 x 40 x 40 cm",
    imageKey: "storage",
    gallery: ["storage", "soft-decor"],
    tags: ["storage", "ottoman", "living", "boucle", "seating"],
    isNew: true,
    popularity: 58,
  }),
];
